### PR TITLE
FIX: allow LOAD_TRUNCATED_IMAGES for pillow

### PR DESCRIPTION
**Pull request by exiledkingcc**

### CODE REVIEW

**Comment by stefan6419846** [comment]
Wouldn't this change have a side effect on all code which imports *pypdf* at some point? If yes, I personally think that this does not belong to *pypdf*, but the user should be made aware of this setting in the docs instead. (For reference: I have a context manager for situations where I expect *Pillow* to silently parse incomplete images, but in most cases, I want *Pillow* to actually fail.)

**Comment by exiledkingcc** [comment]
> Wouldn't this change have a side effect on all code which imports _pypdf_ at some point? If yes, I personally think that this does not belong to _pypdf_, but the user should be made aware of this setting in the docs instead. (For reference: I have a context manager for situations where I expect _Pillow_ to silently parse incomplete images, but in most cases, I want _Pillow_ to actually fail.)

sounds reasonable.

**Comment by pubpub-zz** [comment]
@exiledkingcc do you have an example of truncated image in a pdf ?

**Comment by exiledkingcc** [comment]
> @exiledkingcc do you have an example of truncated image in a pdf ?

i have no examples, but tests have.

**Pull request closed without merging**
