### PR TITLE
ENH: Add clone_from parameter in PdfWriter constructor

### PR DESCRIPTION
**Pull request by pubpub-zz**
add a parameter to ease edition of pdf

### CODE REVIEW

**Comment by pubpub-zz** [comment]
all yours

**Comment by pubpub-zz** [comment]
I don't know if you are waiting for this... but it's all yours 😉

**Comment by MartinThoma** [comment]
Should we deprecate `clone_document_from_reader`?

In general, I think it's a good idea to have only one way to do one thing. This way the code looks more consistent (both internally and externally)

**Comment by pubpub-zz** [comment]
> Should we deprecate `clone_document_from_reader`?
> 
> In general, I think it's a good idea to have only one way to do one thing. This way the code looks more consistent (both internally and externally)

why not.However my only point would be to not break compatibility for existing programs.

**Comment by MartinThoma** [comment]
Yes, I also don't want to break peoples workflows. If we do it, we should use the [deprecation workflow](https://pypdf.readthedocs.io/en/latest/dev/deprecations.html). So `clone_document_from_reader` would stay for quite a while.

**Comment by MartinThoma** [comment]
Thank you for the PR @pubpub-zz :heart:

**Pull request merged**
