### PR TITLE
DOC: Small modification of error message

### PR DESCRIPTION
**Pull request by j-t-1**

### CODE REVIEW

**Comment by j-t-1** [comment]
```
class ViewerPreferences(DictionaryObject):
    def _get_bool(self, key: str, deft: Optional[BooleanObject]) -> BooleanObject:
        return self.get(key, deft)
```

@pubpub-zz what is `deft` here? Can it be renamed for readability?

**Comment by stefan6419846** [comment]
The name is `default`, as you can easily see from its usage as `dict.get(key, default)`.

**Comment by j-t-1** [comment]
It is obvious! I was reading it like a word, and not making the connection. Using "default" instead, would be marginally better? Unsure if good practice to do so.

**Comment by stefan6419846** [comment]
The official name inside the stdlib is `default`: https://docs.python.org/3/library/stdtypes.html#dict.get

**Comment by j-t-1** [comment]
Right. So would be okay to change? Or are you saying because of this it would not be okay to change?

**Comment by stefan6419846** [comment]
It is internal and improves readability, thus changing it is possible and makes sense to avoid doubts.

**Comment by pubpub-zz** [comment]
I prefered not to use `default` as a variable name. I have no objection to change it.

**Pull request merged**
