### PR TITLE
STY: Move functions within _xobj_to_image to a private module

### PR DESCRIPTION
**Pull request by MartinThoma**
This PR only moves code. It does not change any logic.

### CODE REVIEW

**Comment by pubpub-zz** [comment]
Are you sure this will "reduce" the complexity ?
Also In order to ease reading, wouldn't it be better to have also _xobj_to_image in the new file ?

**Comment by MartinThoma** [comment]
I think nested functions are typically more complex then non-nested ones. And passing parameters explicitly is less complex than using global variables.

> In order to ease reading, wouldn't it be better to have also _xobj_to_image in the new file ?

I agree :+1:

**Comment by MartinThoma** [comment]
Ah, damn, if I do that, then it becomes more complicated with PIL (which might not be installed) -.-

**Comment by MartinThoma** [comment]
@pubpub-zz I'm not super happy with this PR as I agree that `_xobj_to_image` should also be in the new module.

However, I think this slightly improves the situation. It does reduce the file size quite a bit and hopefully in a meaningful way: If PRs in future touch often just `filters.py` or `_xobj_image_helpers.py` (one, not both at the same time) it was a good PR. Then it made merge conflicts less likely.

If that is not the case or if you're telling me that this made the situation worse for you, I'll undo it.

**Pull request merged**
