### PR TITLE
BUG: Non-deterministic accidental object reuse

### LINKED ISSUE #1788: Random bug with add_page
With the same environment, i go to have a malformed pdf 

## Environment

```bash
$ python -m platform
Linux-5.19.0-38-generic-x86_64-with-Ubuntu-22.04-jammy

$ python -c "import pypdf;print(pypdf.__version__)"
3.7.1

```

## Code + PDF

```python            

import sys
from pypdf import PdfWriter, PdfReader                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                     
path_out = sys.argv[1]                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                    
output = PdfWriter()                                                                                                                                                                                                                                                                
l_id = []                                                                                                                                                                                                                                                                           
for idx in range(1, 26):                                                                                                                                                                                                                                                            
   r = PdfReader('test/%s.pdf' % idx)                                                                                                                                                                                                                                               
   l_id.append(str(id(r)))                                                                                                                                                                                                                                                          
   for p in r.pages:                                                                                                                                                                                                                                                                
       output.add_page(p)                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                    
output.write(path_out)                                                                                                                                                                                                                                                              
with open(path_out +'.txt', 'w') as fo:                                                                                                                                                                                                                                             
    fo.write("\n".join(l_id)) 
```
Create a directory test with different pdf 
Example pdf: https://file.io/Pn1IwMh9pc5y

I run the program, 50 times
`for i in $(seq 1 50); do python test_concat_pdf.py /tmp/result$i.pdf; done`

# Result
`md5sum /tmp/result*.pdf`
```bash
0ce2c9fb9f5fb8a16fee8c735a64e3a3  /tmp/result33.pdf
18ac040f2467156533b41cc45079436e  /tmp/result10.pdf
18ac040f2467156533b41cc45079436e  /tmp/result11.pdf
18ac040f2467156533b41cc45079436e  /tmp/result12.pdf
18ac040f2467156533b41cc45079436e  /tmp/result13.pdf
18ac040f2467156533b41cc45079436e  /tmp/result14.pdf
18ac040f2467156533b41cc45079436e  /tmp/result15.pdf
18ac040f2467156533b41cc45079436e  /tmp/result16.pdf
18ac040f2467156533b41cc45079436e  /tmp/result17.pdf
18ac040f2467156533b41cc45079436e  /tmp/result18.pdf
18ac040f2467156533b41cc45079436e  /tmp/result19.pdf
18ac040f2467156533b41cc45079436e  /tmp/result1.pdf
18ac040f2467156533b41cc45079436e  /tmp/result20.pdf
18ac040f2467156533b41cc45079436e  /tmp/result21.pdf
18ac040f2467156533b41cc45079436e  /tmp/result22.pdf
18ac040f2467156533b41cc45079436e  /tmp/result23.pdf
18ac040f2467156533b41cc45079436e  /tmp/result24.pdf
18ac040f2467156533b41cc45079436e  /tmp/result25.pdf
18ac040f2467156533b41cc45079436e  /tmp/result26.pdf
18ac040f2467156533b41cc45079436e  /tmp/result27.pdf
18ac040f2467156533b41cc45079436e  /tmp/result28.pdf
18ac040f2467156533b41cc45079436e  /tmp/result29.pdf
18ac040f2467156533b41cc45079436e  /tmp/result2.pdf
18ac040f2467156533b41cc45079436e  /tmp/result30.pdf
18ac040f2467156533b41cc45079436e  /tmp/result31.pdf
18ac040f2467156533b41cc45079436e  /tmp/result32.pdf
18ac040f2467156533b41cc45079436e  /tmp/result34.pdf
18ac040f2467156533b41cc45079436e  /tmp/result35.pdf
18ac040f2467156533b41cc45079436e  /tmp/result36.pdf
18ac040f2467156533b41cc45079436e  /tmp/result37.pdf
18ac040f2467156533b41cc45079436e  /tmp/result38.pdf
18ac040f2467156533b41cc45079436e  /tmp/result39.pdf
18ac040f2467156533b41cc45079436e  /tmp/result3.pdf
18ac040f2467156533b41cc45079436e  /tmp/result40.pdf
18ac040f2467156533b41cc45079436e  /tmp/result41.pdf
18ac040f2467156533b41cc45079436e  /tmp/result42.pdf
18ac040f2467156533b41cc45079436e  /tmp/result43.pdf
18ac040f2467156533b41cc45079436e  /tmp/result44.pdf
18ac040f2467156533b41cc45079436e  /tmp/result45.pdf
18ac040f2467156533b41cc45079436e  /tmp/result46.pdf
18ac040f2467156533b41cc45079436e  /tmp/result47.pdf
18ac040f2467156533b41cc45079436e  /tmp/result48.pdf
18ac040f2467156533b41cc45079436e  /tmp/result49.pdf
18ac040f2467156533b41cc45079436e  /tmp/result4.pdf
18ac040f2467156533b41cc45079436e  /tmp/result50.pdf
18ac040f2467156533b41cc45079436e  /tmp/result5.pdf
18ac040f2467156533b41cc45079436e  /tmp/result6.pdf
18ac040f2467156533b41cc45079436e  /tmp/result7.pdf
18ac040f2467156533b41cc45079436e  /tmp/result8.pdf
18ac040f2467156533b41cc45079436e  /tmp/result9.pdf
```
Here, a pdf is different. It has blank pages.
In the txt file, I have listed the ids of the PdfReader
For the wrong pdf, I have the same id twice (140495761167696)
```
140495777752976                                                                                                                                                                                                                                                                     
140495757290384
140495756671120
140495753673168
140495761167696
140495727106832
140495710644816
140495744436432
140495735690192
140495711730448
140495726845008
140495715144272
140495694350032
140495748724432
140495715062608
140495761167696
140495731812752
140495707371024
140495719364816
140495684779856
140495683795728
140495684528016
140495710266832
140495710765648
14049571560302
```

If I test an alternative script
```python
import sys                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                    
from pypdf import PdfWriter, PdfReader                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                    
path_out = sys.argv[1]                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                    
output = PdfWriter()                                                                                                                                                                                                                                                                
l_id = []                                                                                                                                                                                                                                                                           
l_r = []                                                                                                                                                                                                                                                                            
for idx in range(1, 26):                                                                                                                                                                                                                                                            
   r = PdfReader('test/%s.pdf' % idx)                                                                                                                                                                                                                                               
   l_r.append(r)    
   l_id.append(str(id(r)))    
   for p in r.pages:    
       output.add_page(p)    
    
output.write(path_out)    
with open(path_out +'.txt', 'w') as fo:    
    fo.write("\n".join(l_id))  
```
No problem. Adding the l_id list prevents duplicate ids

I would suggest adding a hash attribute on the PdfReader based on the stream attribute to replace the id method value. What do you think about it?

### PR DESCRIPTION
**Pull request by sjoerdjob**
The following section of code could sometimes have unintended effects where pages of an earlier integrated PDF file were used instead.

```python
writer = PdfWriter()

reader1 = PdfReader(some_file)
id_reader1 = id(reader1)
writer.add_page(reader1.pages[0])
del reader1

reader2 = PdfReader(other_file)
id_reader2 = id(reader2)
writer.add_page(reader2.pages[0])
del reader2

writer.write(third_file)
```

because the `reader1` is no longer in memory when `reader2` gets initialized, the area in memory is free, so `id_reader1` and `id_reader2` might end up having the same value.

Due to PyPDF using `id(reader)` internally for an object-cache, it sometimes happened that `writer.add_page(reader2.pages[0])` would result in duplicating `reader1.pages[0]` instead.

fixes #1788 .

### CODE REVIEW

**Comment by MartinThoma** [comment]
@sjoerdjob Your PR cannot be merged like this as the CI fails:

> pypdf/_protocols.py:68: error: Name "WeakKeyDictionary" is not defined

There are now also a couple of merge conflicts.

**Comment by pubpub-zz** [comment]
@MartinThoma this looks similar (different approach) to a PR you've already about random error. not sure this is still required

**Comment by MartinThoma** [comment]
https://github.com/py-pdf/pypdf/issues/1788 was fixed via https://github.com/py-pdf/pypdf/pull/1841. `test_merging_many_temporary_files` succeeds as well.

**Comment by MartinThoma** [comment]
We didn't have a test that could detect this type of issue, hence I added the test from this PR via https://github.com/py-pdf/pypdf/pull/2244

@sjoerdjob Sorry that it took so long. I'm closing this PR now as the problem was fixed via #1841 and your test was added via https://github.com/py-pdf/pypdf/pull/2244

**Comment by MartinThoma** [comment]
Thank you for your support :hugs: If you want, I'll add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html :-)

**Pull request closed without merging**
