### PR TITLE
MAINT: Update version of deprecation_with_replacement

### PR DESCRIPTION
**Pull request by j-t-1**

### CODE REVIEW

**Comment by stefan6419846** [comment]
Seems like we missed them during the cleanup, as they should already have been removed as well - they already were errors if I am not mistaken. Thus I do not really consider this change to be correct. Depending on whether we yank the 5.0.0 release, this might go into the fixed 5.0.0 release with a complete cleanup.

**Comment by stefan6419846** [comment]
No, I am questioning why we are still delaying the deprecation which - if I understand correctly, should already have happened by completely removing the offending code.

**Comment by j-t-1** [comment]
These were `deprecate_with_replacement` in 4.0.0 and made `deprecation_with_replacement` in #2813, but the 4.0.0 should have been increased to 5.0.0. However, on further consideration, because it is an `__init__.py` file I think it needs to be removed from this file. We are agreeing for its removal but for different reasons.

**Comment by stefan6419846** [comment]
What is your plan on continuing with this? If ever, we should probably update the version number to 6.0 then to indicate that this is gone in version 5.0?

**Comment by j-t-1** [comment]
I think it should be 5.0.0 if I understand the deprecation process. Previously I said being an `__init__.py` file is an issue, but on reflection this is okay as these member functions are not being used, only defined.

**Comment by pubpub-zz** [comment]
Unless I'm wrong :
* in  v3.17.4 and before, we had:
```deprecate_with_replacement((...), "4.0.0")```
this raises a warning saying that the function(s) will be removed in release 4.0.0

in release 4.x.x, the process was not properly applied ( we should have moved to deprecation)

in 5.0.0, the mistake has been fixed and we moved to `deprecation_with_replacement( (....), "4.0.0")
maybe I should have declared 5.0.0.

in 6.0.0, we will completely removed these functions.
OK for me to validate the PR

**Review by stefan6419846 — APPROVED** [review]

**Pull request merged**
