### PR TITLE
STY: Reorder methods in PdfReader and PdfWriter

### PR DESCRIPTION
**Pull request by j-t-1**
Reorder to make more logical, and try to put similar methods in the classes in similar order. Put _repr_mimebundle_ last as it goes less with the other methods.

### CODE REVIEW

**Comment by MartinThoma** [comment]
I'm very skeptical of reordering methods. It's not clear to be if this has any advantage, but the disadvantage is obvious: It becomes very hard to see which PR/commit introduced which line of code.

Additionally, this PR will likely introduce merge conflicts with other PRs + it will be extremely cumbersome to review.

I would close it. What are your thoughts @stefan6419846 / @pubpub-zz ?

**Comment by stefan6419846** [comment]
For me it does not really matter how the methods are ordered as the API docs and autocompletion of IDEs orders them anyway. And yes, this significantly complicates blaming.

**Comment by pubpub-zz** [comment]
> I'm very skeptical of reordering methods. It's not clear to be if this has any advantage, but the disadvantage is obvious: It becomes very hard to see which PR/commit introduced which line of code.
> 
> Additionally, this PR will likely introduce merge conflicts with other PRs + it will be extremely cumbersome to review.
> 
> I would close it. What are your thoughts @stefan6419846 / @pubpub-zz ?

When I did the PR to have common code between PdfReader and PdfWriter, Some orders could have been optimized. I was open to improve this order however, I missed the impact on conflicts resolving and code blaming. I now agree that this will have bad impact.😔

**Comment by j-t-1** [comment]
> I'm very skeptical of reordering methods. It's not clear to be if this has any advantage, but the disadvantage is obvious: It becomes very hard to see which PR/commit introduced which line of code.

This is a fair criticism and has much weighting. At a minimum method is_encrypted should be moved below __init__, as this usually goes first. Putting repr_mimebundle last as it goes less with the other methods if it does not alter any other lines would be good.

When completely new complementary methods are added to both PdfReader and PdfWriter we should try and put them at the end of the class, so the new ones have the same order.

There is a need for having a table (in the documentation say) with rows showing analog methods from PdfReader and PdfWriter (with missing values when analogs do not exist).

**Comment by stefan6419846** [comment]
> There is a need for having a table (in the documentation say) with rows showing analog methods from PdfReader and PdfWriter (with missing values when analogs do not exist).

In my opinion it should be sufficient to enable the class docs for `PdfDocCommon` to indicate common attributes there. Manually maintaining something like this should not be necessary. But this is out of scope for this PR in my opinion.

**Comment by stefan6419846** [comment]
Closing due to the above discussions to favor a clean history over a perfect order.

**Comment by j-t-1** [comment]
> > There is a need for having a table (in the documentation say) with rows showing analog methods from PdfReader and PdfWriter (with missing values when analogs do not exist).
> 
> In my opinion it should be sufficient to enable the class docs for `PdfDocCommon` to indicate common attributes there. Manually maintaining something like this should not be necessary. But this is out of scope for this PR in my opinion.

Did not think of this option. This is a good idea.

**Comment by j-t-1** [comment]
The need for a clean ordering makes sense. I think the only exception is in classes traditionally having `__init__` first.
@pubpub-zz would you be okay puting this first in `ViewerPreferences`?

**Pull request closed without merging**
