### PR TITLE
REL: 4.3.1

### PR DESCRIPTION
**Pull request by MartinThoma**
### Bug Fixes (BUG)
- Cope with Matrix entry in field annotations (#2736)

### Robustness (ROB)
- Cope with fields with upside down box/rectangle (#2729) by @pubpub-zz

### Documentation (DOC)
- Update Link Documentation Example (#2759) by @jparris
- Make table consistent with pdf-version-support.md (#2758) by @j-t-1
- Add feature support by pypdf (#2738) by @j-t-1
- Move JavaScript example (#2746) by @j-t-1
- Added example for downloading a PDF from Google Cloud Storage  (#2745) by @prodeveloper
- Miscellaneous tiny changes (#2744) by @j-t-1
- Amend comment with rectangle duplication (#2733) by @j-t-1
- Use enumerate in extract example (#2727) by @j-t-1
- Tiny changes (#2723) by @j-t-1

### Maintenance (MAINT)
- Remove redundant pass statement (#2739) by @j-t-1
- Update Python version support documentation (#2740) by @j-t-1
- Remove redundant super() (#2734) by @j-t-1
- Add deprecate_with_replacement to StreamObject.initializeFromD… (#2728) by @j-t-1
- Deal with cryptography>=43 moving ARC4 (#2765) by @MartinThoma 

### Code Style (STY)
- Change argument type (#2741) by @j-t-1
- Use endswith instead of logical equals (#2732) by @j-t-1

[Full Changelog](https://github.com/py-pdf/pypdf/compare/4.3.0...4.3.1)

### CODE REVIEW

**Comment by stefan6419846** [comment]
Apparently, there is a (upcoming) breaking change to *cryptography* which affects us and blocks this release.

**Comment by MartinThoma** [comment]
> cryptography.utils.CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.

Interesting. I'll prepare a PR.

**Comment by stefan6419846** [comment]
I just rebased this PR to fix the CI. We probably want to include this change inside the changelog as well.

**Comment by MartinThoma** [comment]
@stefan6419846 done :-) Feel free to merge (I want to see if it then generates the git tag :sweat_smile: )

**Review by stefan6419846 — APPROVED** [review]

**Comment by stefan6419846** [comment]
@stefan6419846 Apparently not, as GitHub Actions does not have the corresponding permission: https://github.com/py-pdf/pypdf/actions/runs/10030795322/job/27720496266

**Pull request merged**
