### PR TITLE
ENH: Add is_open in outlines in PdfReader and PdfWriter

### LINKED ISSUE #1922: Collapsed-by-default outline tree
## Explanation

The outline tree is expanded by default. Child bookmarks are shown. This isn't preferred....(by me).

## Code Example

I've been using PdfWriter.add_outline_item(). I've had no issues using it but can't find any options to collapse the tree

Explained here: https://stackoverflow.com/a/76567193/3631901

pypdf/generic/_data_structures.py, Class TreeObject, def insert_child
```python
if "/Count" in parent:
                parent[NameObject("/Count")] = NumberObject(
                    cast(int, parent[NameObject("/Count")]) + n
                )
                inc_parent_counter(parent.get("/Parent", None), n)

```

becomes

```python
if "/Count" in parent:
                parent[NameObject("/Count")] = NumberObject(0)
                inc_parent_counter(parent.get("/Parent", None), n)
```

I've done very little testing and I've no idea if this is a preferred implementation. It clearly also needs some arguments to drive the configuration option.
Thanks

### PR DESCRIPTION
**Pull request by pubpub-zz**
closes #1922

### CODE REVIEW

**Comment by pubpub-zz** [comment]
ruff/black are applying some correction  (" == True/False" converted into "is True/False") that are inducing some failures 
the rule has not been identified
In the last commit I've fixed it back and locked them with generic # noqa

**Comment by pubpub-zz** [comment]
@MartinThoma 
All yours

**Comment by pubpub-zz** [comment]
@MartinThoma 
any issues for you ?

**Comment by MartinThoma** [comment]
Sorry that it took long :see_no_evil:

**Pull request merged**
