### PR TITLE
BUG: Added check for field /Info when cloning reader document

### PR DESCRIPTION
**Pull request by mnmtz**
Added check for optional field /Info in document root when cloning reader document. (Fixes issue #2049)

### CODE REVIEW

**Comment by stefan6419846** [comment]
Could you please add a corresponding test case as well?

**Comment by pubpub-zz** [comment]
@mnmtz 
What @stefan6419846 means, is can you add a test in test_reader.py: 
you should be able to create a new test function which will create a new pdfwriter with the parameter clone_from receiving the bytes from the url you've posted above.

**Review by pubpub-zz — APPROVED** [review]

**Comment by MartinThoma** [comment]
Thank you for your contribution @mnmtz :-)  If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html :-)

**Comment by MartinThoma** [comment]
I've labeled this with "BUG", because from the users perspective it fixed something that was wrong. This is mainly relevant for where to put it in the CHANGELOG. I doubt any user would get excited about this change, although it's an important improvement. ENH (enhancements, new features) are typically things that were not supported beforehand and expand the capabilities of pypdf.

There are many edge cases. For example, @pubpub-zz recently improved the image support. There I decided to go with ENH, because it were bigger changes

**Pull request merged**
