### PR TITLE
ENH: Extract LaTeX characters

### LINKED ISSUE #2009: Improve math character extraction
## Explanation

Extracting math content is super hard and at the moment completely out of reach (e.g. fractions, subscripts / superscripts, curly braces for two cases, roots). However, maybe we can improve the extraction a little bit by supporting some heavily used single characters:

* hbar: https://www.compart.com/de/unicode/U+0127
* integral: https://www.compart.com/de/unicode/U+222B
* phi
* delta
* alpha
* beta
* gamma
* partial derivative: https://www.compart.com/de/unicode/U+2202
* times
* cdot

## Expectations and current state

File                     |Expected |pypdf|PyMuPDF|PDFium|Tika | Copy-paste from Evince
-------------------------|-------  |-----|-------|------|---- |---
cdot.pdf                 |·        |    |·      |·     |·    |·
hbar.pdf                 |ħ        |~    |ℏ      |~     |~    |~
integral.pdf             |∫        |R    |�      |R     |∫    |R
partial-derivative.pdf   |∂        |@    |∂      |∂     |∂    |∂
phi.pdf                  |φ        |     |φ      |φ     |φ    |φ
varphi.pdf               |φ        |'    |ϕ      |ϕ     |ϕ  | φ

Generated via:

```python
from pypdf import PdfReader
import fitz as PyMuPDF
import pypdfium2 as pdfium
import tika
from tika import parser  # pip install tika

tika.initVM()

def pymupdf_get_text(path) -> str:
    with PyMuPDF.open(path) as doc:
        text = ""
        for page in doc:
            text += page.get_text() + "\n"
    return text

def pdfium_get_text(data: bytes) -> str:
    text = ""
    pdf = pdfium.PdfDocument(data)
    for i in range(len(pdf)):
        page = pdf.get_page(i)
        textpage = page.get_textpage()
        text += textpage.get_text_range() + "\n"
    return text

expected = {
    "integral.pdf": "∫",
    "cdot.pdf": "·",
    "phi.pdf": "φ",
    "varphi.pdf": "φ",
    "partial-derivative.pdf": "∂",
    "hbar.pdf": "ħ",
}

# Print header
file = "File"
expected_str = "Expected"
c_pypdf = "pypdf"
c_pymupdf = "PyMuPDF"
c_pdfium = "PDFium"
c_tika = "Tika"
print(f"{file:<25}|{expected_str:<9}|{c_pypdf:<5}|{c_pymupdf:<7}|{c_pdfium:<6}|{c_tika:<5}")
file = "-" * 25
expected_str = "-------"
c_pypdf = "-----"
c_pymupdf = "-------"
c_pdfium = "------"
c_tika = "----"
print(f"{file:<25}|{expected_str:<9}|{c_pypdf:<5}|{c_pymupdf:<7}|{c_pdfium:<6}|{c_tika:<5}")

# Print data
for file in sorted(expected.keys()):
    expected_str = expected.get(file, 'unknwon')
    c_pypdf = PdfReader(file).pages[0].extract_text().strip()
    c_pymupdf =pymupdf_get_text(file).strip()
    c_pdfium = pdfium_get_text(file).strip()
    c_tika = parser.from_file(file)[ "content" ].strip()
    print(f"{file:<25}|{expected_str:<9}|{c_pypdf:<5}|{c_pymupdf:<7}|{c_pdfium:<6}|{c_tika:<5}")
```

with those files:

* [cdot.pdf](https://github.com/py-pdf/pypdf/files/12145089/cdot.pdf)
* [hbar.pdf](https://github.com/py-pdf/pypdf/files/12145090/hbar.pdf)
* [integral.pdf](https://github.com/py-pdf/pypdf/files/12145091/integral.pdf)
* [partial-derivative.pdf](https://github.com/py-pdf/pypdf/files/12145092/partial-derivative.pdf)
* [phi.pdf](https://github.com/py-pdf/pypdf/files/12145093/phi.pdf)
* [varphi.pdf](https://github.com/py-pdf/pypdf/files/12145094/varphi.pdf)

## Proof that it's relevant

* https://stackoverflow.com/q/76539981/562769
* https://stackoverflow.com/q/53386054/562769
* https://stackoverflow.com/q/48587318/562769
* https://stackoverflow.com/q/66454037/562769

### PR DESCRIPTION
**Pull request by pubpub-zz**
closes #2009

note: code clean up removed duplicates from adobe_glyphs

### CODE REVIEW

**Comment by pubpub-zz** [comment]
@MartinThoma 
I'm interested in your position about phi / phi1 being crossed

**Comment by pubpub-zz** [comment]
except from My comment above, this PR is all yours

**Comment by MartinThoma** [comment]
This is amazing :astonished: :heart_eyes: Thank you so much :hugs:

**Comment by MartinThoma** [comment]
I'm looking forward to the release on the weekend + an update of https://github.com/py-pdf/benchmarks/blob/main/benchmark.py :tada:

**Comment by MartinThoma** [comment]
@pubpub-zz I've [updated the benchmark](https://github.com/py-pdf/benchmarks/commit/9633ada9455eac9d8c7801903cc25a1a45ca51fe):

The text extracting quality metric increased from 96% to 97%. I've also found a couple of places where the ground truth was wrong :tada:  We a now on-par with Tika / PyMuPDF. However, the felt quality is still slightly worse as Tika / PyMuPDF typically deal with whitespaces better.

I had a look at what would be necessary to lift the text extraction to the next step (from a users perspective):



## Local optimizations
Ligature replacement:
* ﬁ should be fi
* ﬂ should be fl
* ﬀ should be ff

I know that this actually goes away from "raw" text extraction, but I think this is what most users want. Maybe we need to re-define  what we want to achieve and potentially add flags / methods for common post-processing :thinking: 

Composed characters:
* `¯x` should be `x̄`
* `ˆx` should be `x̂`

* Chinese characters in [arxiv 2201.00021](https://arxiv.org/pdf/2201.00021.pdf): The name one the first page.
* Removal of hypens inserted solely to fit on the line: Here I'm uncertain. I think most people use the text extraction to do Natural Language Processing (NLP). For them, the hyphens are just noise. But some might need the layout mode to do post-processing on their own. Then hyphen-removal might actually harm.
* [Superscript / subscripts](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts): Especially squares (x²)  and cubes (x³) as well as zero-subscripts (x₀) and one-subscripts (x₁)

## Whitespace
* Most important are inner-word spaces that often occur after the first letter of  a word. See https://github.com/py-pdf/pypdf/issues/1507
* Newlines, especially for [arXiv 2201.00029](https://arxiv.org/pdf/2201.00029.pdf)
* Spaces around math-mode stuff
* Spaces after dots: https://github.com/py-pdf/pypdf/issues/1974

## Layout-mode
* Indentation of code blocks currently completely breaks.
* Multiple newlines to represent paragraph / section boundaries

## Advanced text extraction normalization

This will likely never go into pypdf as it requires a level of document understanding that is likely only achievable with machine learning. Still interesting to think about it:

* Detection of tables + automatic application of layout mode for them, while not using layout mode for e.g. two-column pages. 
* Removal of footers (page numbers)
* Removal of headers
* Removal of spaces used for thousands separation
* Detection of text that belongs to an image / diagram
* Re-structuring of text that is broken up by an image to ensure a smooth text flow

**Pull request merged**
