### PR TITLE
MAINT: Require flit_core >= 3.9

### PR DESCRIPTION
**Pull request by dhgutteridge**

### CODE REVIEW

**Comment by dhgutteridge** [comment]
After change 277643f that went into 3.14, you really need to depend on flit_core >= 3.9, as anything older will fail. E.g., for me, with flit_core 3.8:

* Building wheel...
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 351, in <module>
    main()
  File "/usr/pkg/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 333, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/pkg/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 249, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/usr/pkg/lib/python3.9/site-packages/flit_core/buildapi.py", line 72, in build_wheel
    info = make_wheel_in(pyproj_toml, Path(wheel_directory))
  File "/usr/pkg/lib/python3.9/site-packages/flit_core/wheel.py", line 222, in make_wheel_in
    wb = WheelBuilder.from_ini_path(ini_path, fp)
  File "/usr/pkg/lib/python3.9/site-packages/flit_core/wheel.py", line 87, in from_ini_path
    metadata = common.make_metadata(module, ini_info)
  File "/usr/pkg/lib/python3.9/site-packages/flit_core/common.py", line 410, in make_metadata
    md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
  File "/usr/pkg/lib/python3.9/site-packages/flit_core/common.py", line 207, in get_info_from_module
    docstring, version = get_docstring_and_version_via_import(target)
  File "/usr/pkg/lib/python3.9/site-packages/flit_core/common.py", line 180, in get_docstring_and_version_via_import
    spec.loader.exec_module(m)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "pypdf/__init__.py", line 10, in <module>
    from ._encryption import PasswordType
  File "/home/disciple/pkgsrc/textproc/py-pdf/work/pypdf-3.14.0/pypdf/_encryption.py", line 33, in <module>
    from pypdf._crypt_providers import (
ModuleNotFoundError: No module named 'pypdf'

flit_core 3.9 works for me; I assume it addresses this with the change "A statically defined version number can now be parsed from files called version.py, _version.py or __version__.py inside a packge, as well as from __init__.py, so executing code is required in fewer cases."

**Comment by MartinThoma** [comment]
Can you please help me to reproduce this issue?

The following seems to work fine:

```
$ python -m venv venv
$ source venv/bin/activate
$ pip install flit_core==3.2.0 flit==3.2.0
$ python -m flit build
```

**Comment by dhgutteridge** [comment]
In the case of the downstream project I'm involved with (pkgsrc.org),
we aren't invoking via flit, we're invoking using build. So a roughly
equivalent reproducer for you would be:

python -m venv venv
source venv/bin/activate
pip install flit_core==3.2.0 build
python -m build --wheel --skip-dependency-check --no-isolation

That should reproduce the failure for you (it does for me), same if you
pick 3.8.0 for filt_core. Bumping to 3.9.0 resolves it. (The original
example I shared was on NetBSD, not that it should matter. For purposes
of testing here, I used Fedora Linux 38 instead.)

**Comment by MartinThoma** [comment]
If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by dhgutteridge** [comment]
> If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

Sure, that's nice of you, thanks! Thanks also for maintaining this software. It's part of NetBSD's toolchain for maintaining our published documentation.

**Pull request merged**
