### PR TITLE
MAINT: Adjust type annotations in _rectangle.py

### LINKED ISSUE #1842: API inconsistency in `RectangleObject`?
## Explanation

I guess there is a type mismatch in the API of `RectangleObject`. For example, properties like `.lower_left` (and similar) return a tuple. However, their setter methods take a list object instead of a tuple. Would it be more consistent to take a tuple too?

## Code Example

How would your feature be used? (Remove this if it is not applicable.)

```python
>>> # Current usage
>>> first_page.mediabox.upper_left = [0, 480]

>>> # More consistent?
>>> first_page.mediabox.upper_left = (0, 480)
```

### PR DESCRIPTION
**Pull request by postmeback**
The setters lower_left / lower_right / upper_left / upper_right are now consistent with the getters.

Closes #1842

### CODE REVIEW

**Comment by postmeback** [comment]
Requesting Review

**Comment by MartinThoma** [comment]
Well done, congratulations to your first merged PR! The update will go life latest on Sunday in the next release.

If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by MartinThoma** [comment]
You might have noticed a few adjustments I made in this PR:

* The title: The prefix "MAINT" makes sure it gets recognized by https://github.com/py-pdf/pypdf/blob/main/make_changelog.py . The rest of the line should be something that would speak for itself within the changelog.
* The body: The "closes #1842" makes sure that the issue is closed with this PR once it got merged. That forms a link which others might find valuable. The rest of the body summarizes the outcome of the discussions in the issue.

The title of the PR typically becomes the first line in the squashed commit message. The body becomes the rest of the commit message.

**Comment by postmeback** [comment]
Sure, please add me. @MartinThoma

**Pull request merged**
