### PR TITLE
BUG: Encrypt / decrypt Stream object dictionaries

### PR DESCRIPTION
**Pull request by pilotandy**
Fixes #2227

### CODE REVIEW

**Comment by exiledkingcc** [comment]
this pr can fix #2227 with no doubt. github CI failed due to other problems.

**Comment by stefan6419846** [comment]
Side note: `test_image_without_imagemagic` is a misleading name and rather tests `test_image_without_pillow`.

**Comment by stefan6419846** [comment]
I assume that the failing test is a side-effect of the newly introduced test: `test_image_without_imagemagic` seems to implicitly rely on the fact that `pypdf._xobj_image_helpers` has not been loaded before. The new test retrieves an image, thus probably already importing it, while Python does not re-import already known namespaces. For this reason, the `ImportError` will not be raised here.

One possible solution to circumvent this is by making `test_image_without_imagemagic` completely standalone, for example by doing a subprocess call which checks for the `ImportError`.

**Comment by pubpub-zz** [comment]
@stefan6419846 
thanks for your analysis

@pilotandy 
here is a way to get your test working without calling the to induce the error:
```
def test_encrypt_stream_dictionary(pdf_file_path):
    user_password = secrets.token_urlsafe(10)

    reader = PdfReader(RESOURCE_ROOT / "cmyk_image.pdf")
    page = reader.pages[0]
    original_image_obj = page["/Resources"]["/XObject"]["/I"]

    writer = PdfWriter()
    writer.add_page(reader.pages[0])
    writer.encrypt(
       user_pass
word=user_password,
       owner_password=None,
       algorithm="RC4-128",
    )
    with open(pdf_file_path, "wb") as output_stream:
        writer.write(output_stream)

    reader = PdfReader(pdf_file_path)
    assert reader.is_encrypted
    assert reader.decrypt(user_password) == PasswordType.OWNER_PASSWORD
    page = reader.pages[0]
    decrypted_image_obj = page["/Resources"]["/XObject"]["/I"]
    assert decrypted_image_obj["/ColorSpace"][3] == original_image_obj["/ColorSpace"][3]
```

**Comment by MartinThoma** [comment]
(I've moved/removed a couple of comments from this discussion, as it was not primarily about the PR)

**Comment by MartinThoma** [comment]
@pilotandy May I move the PDF to https://github.com/py-pdf/sample-files  ([docs](https://pypdf.readthedocs.io/en/latest/dev/intro.html?highlight=sample-files))?

I typically want files to be in the sample-files for two reasons:

1. `pypdf` repository size: I want to make sure that it is super easy to get pypdf. That includes that the git repository file size should not get too big. 
2. `sample-files` can be used for other projects easily. I hope that the sample-files repository might get used by other PDF libraries and that we create a good re-usable set of test cases

**Comment by MartinThoma** [comment]
Thank you @pilotandy ! 

If you want,I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html :-)

**Comment by pilotandy** [comment]
You're welcome! PyPDF is awesome! Sorry I'm not too good with github yet :/
You can add me to the contributors list.
Just link it to my github.
Craner, Andy

**Pull request merged**
