### PR TITLE
BUG: Avoid isolating the graphics state multiple times

### LINKED ISSUE #2219: Each page merge will add another graphics state isolation call
Merging a page multiple times will isolate the graphics state multiple times instead of re-using the existing wrapping. This is unecessary and probably should be avoided by checking for an isolated graphics state before doing any wrapping. (This has been reported as a possible enhancement in #2203 as well, but extracted to a dedicated issue to allow easier tracking.)

Caching might be useful to avoid doing "expensive" checks each time.

See https://github.com/pymupdf/PyMuPDF/blob/1c2f1da3eb2541f1c8dbd50acb3a916939c99d3e/src/__init__.py#L9141-L9146 and https://github.com/pymupdf/PyMuPDF/blob/1c2f1da3eb2541f1c8dbd50acb3a916939c99d3e/src/__init__.py#L8864-L8876 for an examle implementation in PyMuPDF.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-6.2.0-10022-tuxedo-x86_64-with-glibc2.35

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.16.2, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=none
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader, PdfWriter


watermark = PdfReader('watermark.pdf').pages[0]

writer = PdfWriter(clone_from='file.pdf')
for page in writer.pages:
    page.merge_page(watermark)
    page.merge_page(watermark)
```

This happens for all PDF files.

Please note that the above example code is minimal, although using the same watermark twice is rather useless in production, but shows the issue anyway. Imagine you want to use two different backgrounds and/or overlays on the same page, which would trigger exactly the same.

## Traceback

Suppose we start with `self._data` of the page being `q\n 841.680[...]0 Do\nQ\n\n \n`. Running the above example leads to `self._data` being `q\nq\nq\n 841[...]ET\nQ\nQ\n\nQ\n`, thus we have isolated the graphics state three times, although once should be enough.

### PR DESCRIPTION
**Pull request by stefan6419846**
Fixes #2219.

### CODE REVIEW

**Comment by stefan6419846** [comment]
The test failures appear to be unrelated to this PR.

**Comment by pubpub-zz** [comment]
We have to be careful: we may be in a situation where we are on two isolated sections next to each other's

**Comment by stefan6419846** [comment]
Do you have an example? Judging from the fact that PyMuPDF basically recommends the approach implemented in this PR, I would assume that this indeed is the correct way.

Citing from https://pymupdf.readthedocs.io/en/latest/recipes-common-issues-and-their-solutions.html#id3:

> **Solution 3.** is completely under your control and only does the minimum corrective action. There is a handy utility method `Page.wrap_contents()` which – as twe [sic] name suggests – **wraps** the page’s `contents` object(s) by the PDF commands `q` and `Q`.
> 
> This solution is extremely fast and the changes to the PDF are minimal. This is useful in situations where incrementally saving the file is desirable – or even a must when the PDF has been digitally signed and you cannot change this status.
>
> 
> We recommend the following snippet to get the situation under control:
> 
> ```python3
> >>> if not page.is_wrapped:
>         page.wrap_contents()
> >>> # start inserting text, images and other objects here
> ```

**Comment by pubpub-zz** [comment]
here you are an example 
[tt.pdf](https://github.com/py-pdf/pypdf/files/12752247/tt.pdf)
here is the output with Pdf Debugger:
(beginning)
image
(end)
image

the two q/Q sequences are at same level and even separated with some operations

**Comment by stefan6419846** [comment]
This PDF file will not be considered to have an isolated graphics state at the moment due to `q 1 1 0.94 rg 1 [...] 144.727 704.276 cm\nQ \nQ \nQ \nn \nQ \n'`, but manually editing the content stream makes this PDF being considered as wrapped, yes. The page geometry does not seem to get modified in your example in a weird manner, thus this would not cause any real issue when adding a watermark for example.

The current check is not cheap, but rather simple to do. What you are proposing seems to be that this check should look at every byte and wrap under the following conditions:

  * The file does not start with a variation of `q` and whitespace.
  * The file does not end with a variation of `Q` and whitespace.
  * The file contains multiple top-level `q` commands.

Am I correct? While this is doable, this will have to scan the whole page content in the worst case (= correct PDF). With the current solution (without the fix from this PR), the PDF file might grow each time I add another layer, which does not seem to be a good solution either, although much easier to implement.

**Comment by stefan6419846** [comment]
The following code snippets would correctly detect the most common variations of the `tt.pdf` example from above as well, although introducing quite some computation overhead and thus I did not yet commit it:

```python3
def has_isolated_graphics_state_in_operations(operations: List[Tuple[Any, Any]]) -> bool:
    level = 0
    last_operation_index = len(operations) - 1
    if last_operation_index == -1:
        # There are no operations, thus no isolation required.
        return True

    for index, (_, operator) in enumerate(operations):
        if index == 0 and operator != b"q":
            # Not isolated at the start.
            return False
        if index == last_operation_index and operator != b"Q":
            # Not isolated at the end.
            return False
        if operator not in {b"q", b"Q"}:
            continue
        # `q` commands are at the start, thus increasing the level.
        level += (1 if operator == b"q" else -1)
        if level <= 0:
            # We have detected a second `q ... Q` pair on the root level.
            return False
    return False


def has_isolated_graphics_state_in_bytes(data: bytes) -> bool:
    data = data.strip(b"".join(WHITESPACES))
    byte_count = len(data)
    if byte_count == 0:
        # Whitespace-only data is considered isolated.
        return True
    isolation_commands = re.finditer(rb"(?P<character>[qQ])" + WHITESPACES_AS_REGEXP + rb"*", data)

    # Fast path: If it does not start isolated, return directly.
    first_command = next(isolation_commands, None)
    if first_command is None:
        # We have some non-whitespace content, but no isolation call at all.
        return False
    if first_command.start("character") != 0 or first_command.group("character") != b"q":
        # The first non-whitespace character should be the isolation call.
        return False
    # We have consumed the first `q` command, thus start at level 1.
    level = 1

    for command in isolation_commands:
        character = command.group("character")
        if command.end("character") == byte_count and character == b"Q":
            # We have a `Q` command at the end. Due to having stopped for non-`q` at the
            # start, this is the expected case.
            return True
        # `q` commands are at the start, thus increasing the level.
        level += (1 if character == b"q" else -1)
        if level <= 0:
            # We have detected a second `q ... Q` pair on the root level.
            return False
    return False
```

**Comment by pubpub-zz** [comment]
@MartinThoma 
I'm still not convince with this PR : 
The code required to identify if isolation is required or not, requires to parse the whole contents even if it is spreaded within multiple stream objects, which will have a strong impact on performances. 
The only advantage is to stay acceptable nesting blocks (used to be >28 ? no limit found in PDF2.0). not sure it worth it as no errors have been reported up to now

**Comment by MartinThoma** [comment]
@pubpub-zz Thank you for your assessment of the situation :pray: 

@stefan6419846 It makes sense to me what pubpub-zz is writing. I tend to close this PR. Is there anything I miss / should additionally consider?

**Comment by stefan6419846** [comment]
*pubpub-zz* usually has more insights into the PDF spec, so I am going to trust the aforementioned comments in this case.

As some context, which is outlined in #2219: I have seen this behavior with the graphics state isolation only being done once in PyMuPDF and from my experience, MuPDF being one of the most stable/fault tolerant PDF library, I considered this to be a good solution. There they only check the first and last character of the content stream, although I have not looked at how they handle content streams which are split up.

In some of my use cases, I am using page merges with three or more overlays for one page, so this will quickly lead to quite some nested graphics state isolation calls, which might not always be necessary.

Having said that, I am fine with closing this PR and the corresponding issue as long as their is no real need and you as the maintainer decide that it is not worth the hassle or lead to quite some unnecessary overhead. As a side effect, implementing this PR allowed me to have a quick look at the inner workings of PDF/*pypdf* and allow me to get a basic grasp of the low-level primitives of PDF, so this PR will always have a positive learning effect for me nevertheless.

**Comment by MartinThoma** [comment]
Thank you for your work with this PR and thank you for taking the time to respond.

I do agree with your comment - MuPDF is good and pubpub-zz has very good understanding of the PDF specs + pypdf.

For this reason, I'm closing this PR and the issue now. If people stumble over that issue, we can re-evaluate / re-open :-)

**Pull request closed without merging**
