### PR TITLE
DEV: Record coverage in subprocesses as well

### PR DESCRIPTION
**Pull request by stefan6419846**

### CODE REVIEW

**Comment by stefan6419846** [comment]
Somehow GitHub does not seem to pick up the configuration - running `COVERAGE_PROCESS_START=pyproject.toml python -m pytest tests --cov=pypdf --cov-append -n auto -vv` locally does indeed show a difference.

**Comment by stefan6419846** [comment]
Assumption: We need to use more recent versions of some dependencies to fix this as the latest version would work this way locally and in another project of mine.

**Comment by pubpub-zz** [comment]
do you have any ideas of which modules needs to be updated and to which minimum version?

**Comment by stefan6419846** [comment]
Most likely *coverage.py* and/or *pytest-cov*, but I have not yet verified this.

**Comment by pubpub-zz** [comment]
is this ready for review ?

**Comment by stefan6419846** [comment]
Yes, this should be ready.

**Review by pubpub-zz — APPROVED** [review]

**Comment by pubpub-zz** [comment]
For information : a failed worker error raised, needing rerun. the message was very obvious

**Pull request merged**
