### PR TITLE
PI: Use __slots__

### PR DESCRIPTION
**Pull request by MartinThoma**
## More information

[An awesome explanation on StackOverflow](https://stackoverflow.com/a/28059785/562769)

## How much is it worth?
It's about a **10x** improvement in performance

Before:
bench-1

After:
bench-2

Text extraction speed according to [the benchmark](https://github.com/py-pdf/benchmarks) is not affected at all :smiling_face_with_tear:

### CODE REVIEW

**Comment by MartinThoma** [comment]
I'm running into https://stackoverflow.com/q/10857515/562769

**Comment by MartinThoma** [comment]
@pubpub-zz Is `indirect_reference` actually a property of `PdfObjectProtocol` / `PdfObject`? I've only seen it on `Page` and `Destination`

**Comment by pubpub-zz** [comment]
Quite. 99% of the time 
This property is only initiated for objects attached to a pdfreader or a PdfWriter. The cloning process checks if this property exists to do some specific actions.

**Comment by MartinThoma** [comment]
There are two places where we assign indirect_reference:

PdfReader:

```
    def cache_indirect_object(
        self, generation: int, idnum: int, obj: Optional[PdfObject]
    ) -> Optional[PdfObject]:
        if (generation, idnum) in self.resolved_objects:
            msg = f"Overwriting cache for {generation} {idnum}"
            if self.strict:
                raise PdfReadError(msg)
            logger_warning(msg, __name__)
        self.resolved_objects[(generation, idnum)] = obj
        if obj is not None:
            obj.indirect_reference = IndirectObject(idnum, generation, self)
        return obj
```

PdfWriter:

```
    def _add_object(self, obj: PdfObject) -> IndirectObject:
        if hasattr(obj, "indirect_reference") and obj.indirect_reference.pdf == self:  # type: ignore
            return obj.indirect_reference  # type: ignore
        self._objects.append(obj)
        obj.indirect_reference = IndirectObject(len(self._objects), 0, self)
        return obj.indirect_reference
```

**Comment by MartinThoma** [comment]
@pubpub-zz  The interesting question is if `FloatObject` and `BooleanObject` ever get an attribute dynamically assigned. I only see dynamic attribute assignment for `indirect_reference` . I also only see it happening in 

* `PdfReader.cache_indirect_object`
* `PdfWriter._add_object`
* `DictionaryObject._clone`

I guess all of them (or at least one) could assign `indirect_reference` to a float object, right?

**Comment by pubpub-zz** [comment]
Although unusual the `indirect_reference` can point to an `FloatObject` and `NumberObject`.

**Comment by MartinThoma** [comment]
Ok, then I'll close it. We need to find another way (or find a way to add indirect_reference to the object while having multiple inheritance)

**Comment by MartinThoma** [comment]
https://stackoverflow.com/questions/472000/usage-of-slots/472024#472024

**Pull request closed without merging**
