### PR TITLE
ROB: Catch keyerror to allow duplicate fields

### PR DESCRIPTION
**Pull request by pcraciunoiu**
Attempt to work around #2234

### CODE REVIEW

**Comment by MartinThoma** [comment]
@stefan6419846 / @pubpub-zz What do you think about this PR?

**Comment by stefan6419846** [comment]
Looking at the linked issues, I do not think that completely silencing these errors is the correct approach, while `logger_warning` does not seem to be correct either - such PDF files just are not supported by *pypdf* now. I would certainly prefer a clean solution as pointed out in https://github.com/py-pdf/pypdf/issues/2234#issuecomment-1743733843.

**Comment by tagirahmad** [comment]
@stefan6419846  @pubpub-zz @pcraciunoiu Will this PR merged? I really need this functionality.

**Comment by stefan6419846** [comment]
@tagirahmad I am no PDF expert, but as pointed out in https://github.com/py-pdf/pypdf/pull/2333#issuecomment-1848941890, the approach from this PR does not seem to be the correct/clean solution we are looking for.

**Comment by pcraciunoiu** [comment]
I agree the solution is just to ignore an error that has a reason, but won't have time to look into the deeper fix anytime soon sadly.

**Comment by pubpub-zz** [comment]
fields could have multiple annotation:display at many places in a document but it is only one field which shall be unique.
allowing many fields with the same name is not a solution

**Comment by stefan6419846** [comment]
Closing in favor of #2570.

**Pull request closed without merging**
