### PR TITLE
BUG: Handle indirect objects in font width calculations

### LINKED ISSUE #2966: Exception thrown when encountering indirect object
The Python library pdfrw (which is what underpins the pdf_redactor library) sometimes generates files that result in the pypdf font size calculations encountering an indirect object.  This results in an exception (either trying to add an int to an IndirectObject, or to divide an IndirectObject by an int).

## Environment

```bash
$ python -m platform
Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.39

(but I've also reproduced it on macOS)

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==5.1.0, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=none
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
import random
import re
import string

import pdf_redactor
import pypdf


def test_repro(match_pattern, replace):
    options = pdf_redactor.RedactorOptions()
    options.content_filters = [
        (re.compile(match_pattern), lambda m: replace),
    ]
    with open('repro_in.pdf', 'rb') as inhandle:
        with open('repro_out.pdf', 'wb') as outhandle:
            options.input_stream = inhandle
            options.output_stream = outhandle
            pdf_redactor.redactor(options)

    # This will result in an unhandled exception if the file
    # successfully reproduces the error
    with open('repro_out.pdf', 'rb') as inhandle:
        r = pypdf.PdfReader(inhandle)
        p = r.pages[0]
        _ = p.extract_text()


test_repro('TEXT', '-')
```

It took a while to provoke pdf_redactor / pdfrw into using an indirect object with a PDF that I could share, and I'm still not 100% certain what causes it to do so, so this PDF (which is a Word document that has been exported to PDF) maybe includes superfluous content. 

[repro_in.pdf](https://github.com/user-attachments/files/17903952/repro_in.pdf)

## Traceback

This is the complete traceback I see:

```
Traceback (most recent call last):
  File "/Users/neil/3rdpartysw/pypdf/repro.py", line 28, in <module>
    test_repro('TEXT', '-')
  File "/Users/neil/3rdpartysw/pypdf/repro.py", line 25, in test_repro
    _ = p.extract_text()
        ^^^^^^^^^^^^^^^^
  File "/Users/neil/3rdpartysw/pypdf/pypdf/_page.py", line 2393, in extract_text
    return self._extract_text(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/neil/3rdpartysw/pypdf/pypdf/_page.py", line 1868, in _extract_text
    cmaps[f] = build_char_map(f, space_width, obj)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/neil/3rdpartysw/pypdf/pypdf/_cmap.py", line 33, in build_char_map
    font_subtype, font_halfspace, font_encoding, font_map = build_char_map_from_dict(
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/neil/3rdpartysw/pypdf/pypdf/_cmap.py", line 60, in build_char_map_from_dict
    half_space_width = compute_space_width(font_width_map, space_key_char) / 2.0
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'IndirectObject' and 'float'
```

After fixing the issue in `build_char_map_from_dict` (which is really in `compute_space_width`), there's a similar exception thrown in `_get_acutual_font_widths` (sic), which stems from `compute_font_width`:

```
Traceback (most recent call last):
  File "/Users/neil/3rdpartysw/pypdf/repro.py", line 28, in <module>
    test_repro('TEXT', '-')
  File "/Users/neil/3rdpartysw/pypdf/repro.py", line 25, in test_repro
    _ = p.extract_text()
        ^^^^^^^^^^^^^^^^
  File "/Users/neil/3rdpartysw/pypdf/pypdf/_page.py", line 2393, in extract_text
    return self._extract_text(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/neil/3rdpartysw/pypdf/pypdf/_page.py", line 2109, in _extract_text
    process_operation(b"Tj", [op])
  File "/Users/neil/3rdpartysw/pypdf/pypdf/_page.py", line 2052, in process_operation
    text, rtl_dir, _actual_str_size = self._handle_tj(
                                      ^^^^^^^^^^^^^^^^
  File "/Users/neil/3rdpartysw/pypdf/pypdf/_page.py", line 1820, in _handle_tj
    self._get_acutual_font_widths(cmap, text_operands, font_size, space_width))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/neil/3rdpartysw/pypdf/pypdf/_page.py", line 1786, in _get_acutual_font_widths
    font_widths += compute_font_width(font_width_map, char)
TypeError: unsupported operand type(s) for +=: 'int' and 'IndirectObject'
```

## Patch

I've forked the repo, and have created a patch that solves this problem for this particular input file. I'll raise a PR for that in a minute. There may, of course, be more complicated scenarios that the patch doesn't handle correctly.

### PR DESCRIPTION
**Pull request by nsw42**
Closes #2966 

This handles indirect objects when calculating font widths

### CODE REVIEW

**Comment by stefan6419846** [comment]
Mmh, the exact issue reported in #2966 apparently is not covered by the tests. Shouldn't it reproduce it and thus find the `IndirectObject` there as you used your example document - or am I missing something?

**Comment by nsw42** [comment]
> Mmh, the exact issue reported in #2966 apparently is not covered by the tests. Shouldn't it reproduce it and thus find the `IndirectObject` there as you used your example document - or am I missing something?

That's what should happen - and the code coverage shows that that is happening, except for one edge case (see below). I also confirmed that the test reproduces the problem by reverting _cmap.py to the version on main, and the test failed with the exception I reported in #2966. 

Re the edge case: I added three checks against `IndirectObject`, one in `compute_font_width` and two in `compute_space_width`. pycov is highlighting the second code path in `compute_space_width`, which is the exception handler for when there's no entry for `space_char` in `font_width_map`. The code used to return `font_width_map["default"] / 2` for that path, and I *assumed* that `font_width_map["default"]` could be an `IndirectObject`, in the same way that the exception demonstrated that `font_width_map[space_char]` could be. I therefore added a test against `IndirectObject` within the exception handler. I don't have a way of constructing a PDF that would trigger that code path, hence the lack of coverage for that line. The other two tests against `IndirectObject` were covered by the new test.

Hope that makes sense, but let me know if I'm wrong about the possibility of `font_width_map["default"]` being an `IndirectObject`.

**Comment by stefan6419846** [comment]
Skimming through the code, the only place where `font_width_map["default"]` is written and could be an `IndirectObject` seems to be https://github.com/nsw42/pypdf/blob/795be0a421cb57b3a6883573f46330d1f812fe04/pypdf/_cmap.py#L409 My recommendation would be to rewrite this section/exception handling instead and revert the currently not covered line:

```python3
        if "/DW" in ft1:
            font_width_map["default"] = cast(float, ft1["/DW"].get_object())
        else:
            font_width_map["default"] = default_font_width
```

Please note that I have not tested this myself, but IMHO `Exception` can only be `KeyError` here which we can prevent directly.

**Comment by nsw42** [comment]
> ... the only place where `font_width_map["default"]` is written and could be an `IndirectObject` seems to be https://github.com/nsw42/pypdf/blob/795be0a421cb57b3a6883573f46330d1f812fe04/pypdf/_cmap.py#L409
> My recommendation would be to rewrite this section/exception handling instead and revert the currently not covered line
> ...

Thanks for the extra insight. Happy to revert the not covered line. 

Indeed, by pointing at `build_font_width_map`, you've made me realise that the problem is actually in there, not in the places I changed: `font_width_map` (accessed in the functions changed in my original PR) has been assigned the return value from `build_font_width_map`, and that return value is not complying with its declared type hint of `Dict[Any, float]`, because some of the values in the dict are `IndirectObject`s. So, the better approach is probably to rework the PR to avoid indirect objects in the dictionary values.

Another thing I noticed looking at `build_font_width_map`: the assignment to `default_font_width` is missing the parentheses to call `get_object`, meaning that the lookup in `_default_fonts_space_width` will *always* result in a `KeyError`. So, I will fix that.

Since raising the bug report and opening the PR, I've since seen #2286, so a variant of this problem has been seen and fixed before; so it looks like a recent regression.   But, nonetheless, it seems challenging to provoke PDF libraries to create files that cover all code paths through that function. I'm therefore going to change only the code path(s) that I can see encounter an `IndirectObject`.

**Comment by stefan6419846** [comment]
> Since raising the bug report and opening the PR, I've since seen https://github.com/py-pdf/pypdf/issues/2286, so a variant of this problem has been seen and fixed before; so it looks like a recent regression. But, nonetheless, it seems challenging to provoke PDF libraries to create files that cover all code paths through that function.

Unresolved `IndirectObjects` indeed tend to be a recurring theme and I just stumbled upon another location this week as well (#2965). We can only solve this gradually once we see such cases in the wild and add corresponding tests to avoid these in the future. You can find lots of PDF files with use special constructs or partially violate the standard as well. Thus covering all cases without exposing confidential data is a common topic and sometimes requires extended knowledge of the specification and/or manually editing files with a text editor and similar.

About the regression part, I am not sure - this would require verification with older *pypdf* versions. It might just be one of the aforementioned cases we never had test coverage for (despite the corresponding line possibly be marked as covered for other reasons).

**Comment by nsw42** [comment]
> Unresolved `IndirectObjects` indeed tend to be a recurring theme and I just stumbled upon another location this week as well (#2965). We can only solve this gradually once we see such cases in the wild and add corresponding tests to avoid these in the future.

Makes sense.  

I've compromised slightly on my previous stance of only adding checks for `IndirectObject` that I could demonstrate with a test. The updated PR has now got two checks for `IndirectObject`; the [`isinstance(second, int)` code path](https://github.com/nsw42/pypdf/blob/b6b4bcdf8f8d3bb3dcd3cbde9e712aac5c8dbd32/pypdf/_cmap.py#L423) is covered by the test. Although I can't provoke it, it seemed sensible to add the corresponding handling of `IndirectObject` in the `isinstance(second, list)` branch a few lines later in the same loop.

**Comment by stefan6419846** [comment]
Thanks. I have committed some further simplifications of the code and will probably merge it later on.

**Review by stefan6419846 — APPROVED** [review]
Thanks for the report and fix.

**Comment by nsw42** [comment]
> Thanks for the report and fix.

Thanks for your patience as I learned about PDF document internal structure and the library implementation.

**Pull request merged**
