### PR TITLE
DEP: Remove paeth_predictor

### PR DESCRIPTION
**Pull request by j-t-1**

### CODE REVIEW

**Comment by stefan6419846** [comment]
IMHO this just reduces readability instead of really simplifying it.

**Comment by j-t-1** [comment]
Maybe there is another way to refactor to avoid the if statement, as this is just a map reduce.

**Comment by j-t-1** [comment]
paeth_predictor is only used to test itself; it is not used elsewhere. The functionality of this function is at line 221 of filters.py.

1. We remove paeth_predictor.
2. We use paeth_predictor in filters.py.

Thoughts?

**Comment by stefan6419846** [comment]
There apparently have been plans by @MartinThoma to deprecate and finally drop this method in https://github.com/py-pdf/pypdf/pull/2068#issuecomment-1669468061, but for now this apparently did not have any real priority.

**Comment by j-t-1** [comment]
Thanks @stefan6419846.

What about moving paeth_predictor to filters.py (it is only used in this file) and calling it within _decode_png_prediction.

**Comment by stefan6419846** [comment]
Where is it used in `filters.py`? As far as I have seen, it is used nowhere and thus most likely can be removed. (As it is not part of a public module, we could even avoid the deprecation.)

**Comment by j-t-1** [comment]
The body of paeth_predictor is on line 221.

**Comment by pubpub-zz** [comment]
I agree to remove it.

**Review by stefan6419846 — APPROVED** [review]

**Pull request merged**
