### PR TITLE
BUG: Add the TK.SIZE into the trailer

### LINKED ISSUE #1901: Missing "Size" info in the trailer
Hi,

I use WeasyPrint to create PDF.
I recently upgraded my libraries to WeasyPrint 59.0 and pypdf 3.10.0.

My aim is to get the trailer of a PDF I created with WeasyPrint. In this trailer, I need the "Size" field, among others.

Previously, I got something like:
```python
{'/Size': 14, '/Root': IndirectObject(3, 0, 140016423632752), '/Info': IndirectObject(2, 0, 140016423632752)}
```
Now, I get something like:
```python
{'/Root': IndirectObject(3, 0, 140470815616880), '/Info': IndirectObject(2, 0, 140470815616880)}
```

If I force WeasyPrint to create a 1.4-versioned PDF, I get the trailer I expect.
However, this is not what I want. It would be much better not to force the 1.4 version.

## Environment

- OS: Debian 11
- Python: 3.9.2
- WeasyPrint: 59.0
- PyPDF: 3.10.0

## Code + PDF

```python
from pypdf import PdfReader

reader = PdfReader("example.pdf")
trailer = reader.trailer.get_object()
```

Here are two PDF samples:
- no version forced : [hello.pdf](https://github.com/py-pdf/pypdf/files/11818298/hello.pdf)
-  1.4 version forced : [hello_1.4.pdf](https://github.com/py-pdf/pypdf/files/11817365/hello_1.4.pdf)

## Suggestion

I have had a look at pypdf source code.
Correct me if I am wrong, but I think my issue is related to the "_read_xref_tables_and_trailers" function of the [reader class](https://pypdf.readthedocs.io/en/stable/_modules/pypdf/_reader.html), where trailer keys are defined that way: "trailer_keys = TK.ROOT, TK.ENCRYPT, TK.INFO, TK.ID"

If you need some more information, I would be glad to provide them.
Thank you for your help.

Alcher

### PR DESCRIPTION
**Pull request by talcher**
Closes #1901

### CODE REVIEW

**Comment by MartinThoma** [comment]
Looks fine to me. 

From "Table 15 – Entries in the file trailer dictionary" of the 1.7 specs:

> (Required; shall not be an indirect reference) The total number of entries in
the file’s cross-reference table, as defined by the combination of the original
section and all update sections. Equivalently, this value shall be 1 greater
than the highest object number defined in the file.
>
> Any object in a cross-reference section whose number is greater than this
value shall be ignored and defined to be missing by a conforming reader.

I wonder why this wasn't observed earlier.

@pubpub-zz What do you think?

**Comment by pubpub-zz** [comment]
Mod looks good. Can you just a check that the /Size is present:
I propose just to add at the end of  one test to confirm Size will not disappear (picked up randomly 😉):
```
@pytest.mark.enable_socket()
    def test_append_forms():
    # from #1538
    writer = PdfWriter()

    url = "https://github.com/py-pdf/pypdf/files/10367412/pdfa.pdf"
    name = "form_a.pdf"
    reader1 = PdfReader(BytesIO(get_pdf_from_url(url, name=name)))
    reader1.add_form_topname("form_a")
    writer.append(reader1)

    url = "https://github.com/py-pdf/pypdf/files/10367413/pdfb.pdf"
    name = "form_b.pdf"
    reader2 = PdfReader(BytesIO(get_pdf_from_url(url, name=name)))
    reader2.add_form_topname("form_b")
    writer.append(reader2)

    b = BytesIO()
    writer.write(b)
    reader = PdfReader(b)
    assert len(reader.get_form_text_fields()) == len(
        reader1.get_form_text_fields()
    ) + len(reader2.get_form_text_fields())
   assert "/Size" in reader.trailer                          # <----  added
```

**Comment by talcher** [comment]
The check is added. I hope the test I chose is OK for you.
The problem is: a codecov check is unsuccessful and the PR does not have a green tick anymore, but a red cross.
Any idea to correct that?

**Comment by MartinThoma** [comment]
Thank you for the contribution! The fix is now in `main`. A new version of pypdf will be on PyPI latest on Sunday (2nd of June, 2023)

**Comment by MartinThoma** [comment]
If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html :-)

**Pull request merged**
