### PR TITLE
ENH: Add Jupyter Notebook integration for PdfReader

### PR DESCRIPTION
**Pull request by MartinThoma**
See

* https://ipython.readthedocs.io/en/stable/config/integrating.html#MyObject._repr_mimebundle_
* https://discourse.jupyter.org/t/what-are-include-exclude-parameter-in-repr-mimebundle-for/23125

## Without this PR

image

## With this PR

image

### CODE REVIEW

**Comment by MartinThoma** [comment]
I could not find any documentation regarding the include / exclude parameters, but ChatGPT thinks it should be used like this (which sounds reasonable):

```python
def _repr_mimebundle_(self, include=None, exclude=None):
    data = {
        'text/plain': 'This is a plain text representation.',
        'text/html': '<strong>This is an HTML representation.</strong>',
        'application/json': '{"key": "value"}'
    }

    if include is not None:
        # Filter representations based on include list
        data = {k: v for k, v in data.items() if k in include}

    if exclude is not None:
        # Remove representations based on exclude list
        data = {k: v for k, v in data.items() if k not in exclude}

    return data
```

**Comment by MartinThoma** [comment]
We could add something similar for PdfWriter and PageObject. Maybe even for annotations (creating a reader and a blank page + adding the annotation + rendering it)

**Comment by stefan6419846** [comment]
Upstream implementation: https://github.com/ipython/ipython/blob/d0e254420445c2204a2b39d28948cd6127717fb1/IPython/core/formatters.py#L151-L157

**Comment by MartinThoma** [comment]
Thanks! Then the ChatGPT code is perfect :tada:

**Pull request merged**
