### PR TITLE
ROB: Soft failure for flate encode image mode 1 with wrong LUT size

### LINKED ISSUE #2889: PdfReadError: Too many lookup values while extracting image
## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-13.6.7-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==4.3.1, crypt_provider=('pycryptodome', '3.20.0'), PIL=10.4.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader
reader = PdfReader('New York State 100AnnvBook140701final10.pdf')

for page in reader.pages:
    print(page)
    for image in page.images:
        print(image)
        print(image.image)
```

[New York State 100AnnvBook140701final10.pdf](https://github.com/user-attachments/files/17252701/New.York.State.100AnnvBook140701final10.pdf)

## Traceback

```
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-BrYcfkKs-py3.11/lib/python3.11/site-packages/pypdf/_page.py", line 2454, in __iter__
    yield self[i]
          ~~~~^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-BrYcfkKs-py3.11/lib/python3.11/site-packages/pypdf/_page.py", line 2450, in __getitem__
    return self.get_function(lst[index])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-BrYcfkKs-py3.11/lib/python3.11/site-packages/pypdf/_page.py", line 490, in _get_image
    imgd = _xobj_to_image(cast(DictionaryObject, xobjs[id]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-BrYcfkKs-py3.11/lib/python3.11/site-packages/pypdf/filters.py", line 791, in _xobj_to_image
    img, image_format, extension, _ = _handle_flate(
                                      ^^^^^^^^^^^^^^
  File "/Users/uzor/Library/Caches/pypoetry/virtualenvs/clown-sort-BrYcfkKs-py3.11/lib/python3.11/site-packages/pypdf/_xobj_image_helpers.py", line 218, in _handle_flate
    raise PdfReadError(
pypdf.errors.PdfReadError: Too many lookup values: Expected 8, got 1016.
```

### PR DESCRIPTION
**Pull request by stefan6419846**
Closes #2889.

### CODE REVIEW

**Comment by pubpub-zz** [comment]
Is it possible to build tests from the pdf provided in the issue ?

**Comment by stefan6419846** [comment]
While it is possible, I honestly do not see the need for this here. The existing test already runs on an artificial 3x3 pixel image and covers all edge cases for the LUT. Adding another test does not really have any benefit IMHO and just requires downloading more data.

**Comment by pubpub-zz** [comment]
> While it is possible, I honestly do not see the need for this here. The existing test already runs on an artificial 3x3 pixel image and covers all edge cases for the LUT. Adding another test does not really have any benefit IMHO and just requires downloading more data.

I understand and agree with what you mean. My point is just I prefer to use actual data to be able to compare pypdf behavior versus other libraries/viewers.

**Comment by stefan6419846** [comment]
I would argue that this is not what tests are about - tests should be written to ensure that everything covered by them is working correctly and does not break for whatever reason. If we are able to ensure this with a small dummy image, this is much easier than downloading at least 1 MB of data beforehand and essentially verifying that no error is raised by default - with the small dummy image, we are able to verify the extraction result directly from within code as well.

Where are we doing a comparison at the moment? We might have a table or written list and some benchmarking, but nothing which would indicate this from a test perspective. Nothing prevents us to use actual data in the case that we explicitly need comparison code later on.

**Review by pubpub-zz — APPROVED** [review]

**Comment by pubpub-zz** [comment]
Sorry if you though I was waiting for something. Just a little overbusy

**Comment by stefan6419846** [comment]
No worries - I just added on your comment and would have waited for the discussion result anyway.

**Pull request merged**
