### PR TITLE
PI: optimize _decode_png_prediction

### PR DESCRIPTION
**Pull request by exiledkingcc**
this commit makes `tests/test_page.py::test_image_new_property` cost from 8.98s to 5.69s on my machine, about x1.5 faster.

### CODE REVIEW

**Comment by pubpub-zz** [comment]
unless I'm wrong, this filter is only for images: wouldn't it be more efficient to use pillow ? your opinion?

**Comment by exiledkingcc** [comment]
i can not find any thing like this in `Pillow`. do you have any idea how to do it with pillow ?

**Comment by MartinThoma** [comment]
I'm updating the test code a bit ( https://github.com/py-pdf/pypdf/pull/2072 ), but this improvement will almost certainly go into the release this weekend :-)

**Comment by MartinThoma** [comment]
I would like to add a new benchmark for this as well (before I merge, so that we can see the difference).

The [current benchmarks](https://py-pdf.github.io/pypdf/dev/bench/) are not really helpful. Lets see if such a big change is visible.

**Comment by pubpub-zz** [comment]
> i can not find any thing like this in `Pillow`. do you have any idea how to do it with pillow ?

I had a quick review and found no solution.😳

**Comment by MartinThoma** [comment]
https://py-pdf.github.io/pypdf/dev/bench/ -> look at the very bottom :-) (I'll share a screenshot once CI is done)

**Comment by exiledkingcc** [comment]
there is a huge mount of math calculations in the method, which is Python's weeknees. besides, it costs a lot of time for pillow to save png file.

**Pull request merged**
