### PR TITLE
BUG: Correctly handle image mode 1 with FlateDecode

### LINKED ISSUE #2248: Incorrect handling of FlateDecode with image mode "1"
Extracting `/FlateDecode` images with an image mode of `1` currently fails, probably due to an invalid range loop.

Let's consider the lookup of `b'\x00p\xc0\xff\xff\xff'` in RGB mode. This should always create two RGB values for further processing ("high" and "low" for image mode `1`), but currently only creates one.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.14.21-150400.24.84-default-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.16.3, crypt_provider=('pycryptodome', '3.18.0'), PIL=10.0.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader

path = 'Prototype-Declaration-VDE4110-HYD-5000-20000-ZSS-DE.pdf'
for index, page in enumerate(PdfReader(path).pages):
    for key in page.images.keys():
        print(key)
        print(page.images[key].indirect_reference)
```

An example file is [this](https://github.com/py-pdf/pypdf/files/12847339/Prototype-Declaration-VDE4110-HYD-5000-20000-ZSS-DE.pdf)

## Traceback

This is the complete traceback I see:

```
Traceback (most recent call last):
  File "/home/stefan/temp/run.py", line 15, in <module>
    print(page.images[key].indirect_reference)
  File "/home/stefan/temp/venv/lib/python3.9/site-packages/pypdf/_page.py", line 2709, in __getitem__
    return self.get_function(index)
  File "/home/stefan/temp/venv/lib/python3.9/site-packages/pypdf/_page.py", line 558, in _get_image
    return self._get_image(ids, cast(DictionaryObject, xobjs[id[0]]))
  File "/home/stefan/temp/venv/lib/python3.9/site-packages/pypdf/_page.py", line 547, in _get_image
    imgd = _xobj_to_image(cast(DictionaryObject, xobjs[id]))
  File "/home/stefan/temp/venv/lib/python3.9/site-packages/pypdf/filters.py", line 781, in _xobj_to_image
    img, image_format, extension, invert_color = _handle_flate(
  File "/home/stefan/temp/venv/lib/python3.9/site-packages/pypdf/_xobj_image_helpers.py", line 177, in _handle_flate
    [
  File "/home/stefan/temp/venv/lib/python3.9/site-packages/pypdf/_xobj_image_helpers.py", line 179, in <listcomp>
    [
  File "/home/stefan/temp/venv/lib/python3.9/site-packages/pypdf/_xobj_image_helpers.py", line 180, in <listcomp>
    colors_arr[1 if img.getpixel((x, y)) > 127 else 0]
IndexError: list index out of range
```

### PR DESCRIPTION
**Pull request by stefan6419846**
Fixes #2248.

### CODE REVIEW

**Comment by stefan6419846** [comment]
I am not sure about the AES failures in this case, which seems to be an issue wit older Python versions and the used test file. In theory we could skip the tests for Python < 3.9(?), but this does not really seem right.

**Comment by MartinThoma** [comment]
@exiledkingcc Could you please have a look at it?

**Comment by stefan6419846** [comment]
As another data point: It seems like this only affects Python 3.7 where neither `pycryptodome` nor `cryptography` are being installed. Why do we apparently not test Python 3.7 with AES encryption at all?

For reference: https://github.com/stefan6419846/pypdf/actions/runs/6469234606/ uses the same code as the branch of this PR, but with *fail-fast* disabled compared to the "original" PR run in https://github.com/py-pdf/pypdf/actions/runs/6458194919/

**Comment by exiledkingcc** [comment]
the test pdf file is encrypted with empty password. so is ok to skip if no AES decrypting.
pytests for Python 3.7 without  `pycryptodome` and `cryptography` is just to make pytests simple.
no need to test `pycryptodome` or `cryptography` or none oth them for every python versions.

**Comment by stefan6419846** [comment]
@MartinThoma I would argue that we could indeed merge this then. Discussing how to continue with one Python version not being tested with encryption should probably be a separate issue/PR in this case - just adding another matrix entry should be sufficient and if desired, I am open to providing a corresponding PR for it.

**Comment by MartinThoma** [comment]
Thank you @stefan6419846 for reporting the issue and for fixing it :pray: 

Yes, it would be nice to complete our CI to ensure we don't have relevant gaps in test coverage

**Comment by MartinThoma** [comment]
@exiledkingcc Thanks for having a look :pray:

**Pull request merged**
