### PR TITLE
ENH: accepts ETen-B5 and UniCNS-UTF16 encodings

### LINKED ISSUE #2356: Implementation of advanced cmap encodings
Currently, I am trying to extract text from PDF files which partially report some warnings like

```
/home/stefan/temp/venv/lib/python3.9/site-packages/pypdf/_cmap.py:183: PdfReadWarning: Advanced encoding /GBK2K-H not implemented yet
  warnings.warn(
/home/stefan/temp/venv/lib/python3.9/site-packages/pypdf/_cmap.py:183: PdfReadWarning: Advanced encoding /GBK2K-V not implemented yet
  warnings.warn(
```

I have seen this for the both encodings mentioned above and for `/StandardEncoding`.

Digging through the available resources related to the GBK2K cmaps, I found some Adobe resources as well as the implementation from `pdfminer.six`, which ships some custom pickled files derived from the Adobe open source components to handle such cases.

Is there any guidance available on how to tackle this or how we would like to see this added to *pypdf*?

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.14.21-150400.24.100-default-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.3, crypt_provider=('pycryptodome', '3.18.0'), PIL=10.0.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader

reader = PdfReader('file.pdf')
page = reader.pages[0]
print(page.extract_text())
```

For now, I have no uncritical file I could share here. Looking at the example file, it seems like in this case it is a scan of a document (from a Canon device?) with Latin characters with wrongly configured or strange OCR, yielding a mix of Latin and Chinese characters inside the text layer. 

## Traceback

`warnings.warn` as currently used only prints the *pypdf* code line this occurred, thus there is not much of a traceback.

### PR DESCRIPTION
**Pull request by pubpub-zz**
Related to #2356

### CODE REVIEW

**Comment by stefan6419846** [comment]
There are three aspects I am not sure about:

* Do we really need the `TBC` comments inside the mapping?
* If we have possibly public PDF files, shouldn't we add at least a basic test.
* We should not close #2536 with this - there are still unsupported encodings left, as indicated by the "TBC" comments as well.

**Comment by pubpub-zz** [comment]
> There are three aspects I am not sure about:
> 
>     * Do we really need the `TBC` comments inside the mapping?

The TBC are just here to wait from feed back from @actuary-chen

> 
>     * If we have possibly public PDF files, shouldn't we add at least a basic test.

I did not focus as this should not be easily subject to regressio on it but I agree it should be better

> 
>     * We should not close [PdfReader - Extract images from specific pages #2536](https://github.com/py-pdf/pypdf/discussions/2536) with this - there are still unsupported encodings left, as indicated by the "TBC" comments as well.

I dislike the Idea of having a garbage collecting issue on this subject : We need to have some test file to confirm the proper encoding; I prefer new issue to raised on case per case.

**Comment by pubpub-zz** [comment]
I'veremoved all TBC. Let's wait a litte for some feedbacks from @actuary-chen for the last entries

**Comment by stefan6419846** [comment]
> I dislike the Idea of having a garbage collecting issue on this subject : We need to have some test file to confirm the proper encoding; I prefer new issue to raised on case per case.

I initially opened the corresponding issue to discuss how this could be done in general or whether there might be any official test documents which would allow us to cover all cases without having lots of small commits for it.

**Comment by actuary-chen** [comment]
I can only confirm no wording shows as "pypdf._cmap: implementation of
advance cmap ...."
However, I cannot make sure whether the text is correct to decode or not,
because I use it in the embedding model to a vector database.

codecov[bot] ***@***.***> 於 2024年6月22日 週六 下午6:20寫道：

**Comment by actuary-chen** [comment]
It sounds good after I retrieve some texts from the database.


Benjamin Chen ***@***.***> 於 2024年6月23日 週日 上午5:25寫道：

**Review by stefan6419846 — APPROVED** [review]

**Pull request merged**
