### PR TITLE
TST: Add LzwCodec for encoding

### PR DESCRIPTION
**Pull request by MartinThoma**
This is a change I wanted to do for a while :-)

While we might only need decoding for pypdf, having both decoding and encoding in one class massively helps with testing. We can still get it wrong, but it's harder to get both the encoder and the decoder wrong in a consistent way.

This PR adds an abstract `Codec` class as well as an LzwCodec implementation.

We could even use [hypothesis](https://pypi.org/project/hypothesis/) for property-based testing for all codecs :-)

### CODE REVIEW

**Comment by pubpub-zz** [comment]
can you clarify what you intend to do with the encoding?

**Comment by MartinThoma** [comment]
I want to have an easy way to check if the decoding does the right thing.

This allows us to change the LZW implementation with the confidence that we don't break workflows.

**Comment by MartinThoma** [comment]
@Lucas-C Maybe the encoder is interesting for fpdf2? It wasn't in any discussion, but only mentioned in https://github.com/py-pdf/fpdf2/issues/691

**Comment by stefan6419846** [comment]
I would recommend to make the encoder roughly the same as the decoder, id est passing `data` to `__init__` instead.

**Comment by MartinThoma** [comment]
@stefan6419846 Done :-) :+1:

**Comment by stefan6419846** [comment]
Are we sure that we want to expose this as a public module while we do not officially support encoding objects with LZW? I tend to make `codecs` an internal module for now.

**Comment by pubpub-zz** [comment]
Codecs might be kept private and called directly from filters.

For the tests,  as it currently is, you have proved that you have a function and the inverted function : I would have liked to have a minimum test that check also the compressed data

**Comment by MartinThoma** [comment]
Good point, I made it private. I'm uncertain about the module name, but as it is private it should not matter too much.

**Comment by MartinThoma** [comment]
@pubpub-zz You're absolutely right. I've added two examples. I would feel even better if there was documented (non-encoded, encoded) pairs that we could add to the test suite, but for now that should be fine.

**Review by stefan6419846 — APPROVED** [review]

**Comment by Lucas-C** [comment]
> @Lucas-C Maybe the encoder is interesting for fpdf2? It wasn't in any discussion, but only mentioned in [py-pdf/fpdf2#691](https://github.com/py-pdf/fpdf2/issues/691)

Yes, it could make for an interesting addition!
Thank you for the ping.

I opened https://github.com/py-pdf/fpdf2/issues/1271 to suggest this feature.
Maybe it will be picked up during [Hacktoberfest](https://hacktoberfest.com/)!

Just to be clear @MartinThoma : are you explicitly allowing `fpdf2` to include the code included in this PR?

**Pull request merged**
