### PR TITLE
MAINT: remove unused code

### PR DESCRIPTION
**Pull request by pubpub-zz**
remove _get_page from reader which is redundant with get_page
faced again some issues with a broken link from tika. Replace them with github links.

### CODE REVIEW

**Comment by stefan6419846** [comment]
> tika files (links are dissapearing progressively)

Is there any official indication about this?

**Comment by pubpub-zz** [comment]
(examples_files.yaml)
[tika-908104.pdf](https://github.com/user-attachments/files/16676292/tika-908104.pdf)
[tika-923406.pdf](https://github.com/user-attachments/files/16676293/tika-923406.pdf)
[tika-955562.pdf](https://github.com/user-attachments/files/16676295/tika-955562.pdf)
[tika-959173.pdf](https://github.com/user-attachments/files/16676297/tika-959173.pdf)
[tika-957144.pdf](https://github.com/user-attachments/files/16676308/tika-957144.pdf)
[tika-952445.pdf](https://github.com/user-attachments/files/16676335/tika-952445.pdf)
[tika-921632.pdf](https://github.com/user-attachments/files/16676334/tika-921632.pdf)
[tika-976970.pdf](https://github.com/user-attachments/files/16676340/tika-976970.pdf)
[tika-976970.pdf](https://github.com/user-attachments/files/16676346/tika-976970.pdf)
[tika-914102.pdf](https://github.com/user-attachments/files/16676352/tika-914102.pdf)
[tika-924546.pdf](https://github.com/user-attachments/files/16676366/tika-924546.pdf)
[tika-972174.pdf](https://github.com/user-attachments/files/16676369/tika-972174.pdf)

**Comment by stefan6419846** [comment]
I tend to prefer this to be done only if there is real need to do so. Additionally, it might make sense as well to review the files before just adding them. There must be reasons why they have been deleted and I am not always sure whether we really need them or whether we could replace them with another one.

**Comment by pubpub-zz** [comment]
> Additionally, it might make sense as well to review the files before just adding them. 

All thèse files have been added based on different PRs added for years. @MartinThoma reported them.
Today they provide a good pool of test file


There must be reasons why they have been deleted and I am not always sure whether we really need them or whether we could replace them with another one.

@MartinThoma do you have any idea why links become dead?
Providing replacement is a hudge job. These where reported from a major apache 2.0 project. The licence analysis was for me good enough.

**Review by stefan6419846 — APPROVED** [review]

**Pull request merged**
