### PR TITLE
BUG: Prevent infinite loop when no character follows after a comment

### LINKED ISSUE #1825: pypdf hangs on one specific PDF - cannot catch error with try/except
pypdf freezes on one specific PDF. I get no error, and no succeed. I am not able to see what the error is.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-12.3.1-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf.__version__)"
3.8.1
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader

reader = PdfReader("example.pdf")
number_of_pages = len(reader.pages)
page = reader.pages[0]
text = page.extract_text()
```
The PDF is shared below. This is a publicly-accessible PDF.

[MiFO_LFO_FEIS_NOA_Published (3).pdf](https://github.com/py-pdf/pypdf/files/11367871/MiFO_LFO_FEIS_NOA_Published.3.pdf)

Any thoughts as to why this particular pdf might hang?

### PR DESCRIPTION
**Pull request by exiledkingcc**
Fixes #1825

### CODE REVIEW

**Review by pubpub-zz — APPROVED** [review]
Can you add the test refering the pdf refered in #1825

**Comment by pubpub-zz** [comment]
great. Just be aware that test running on the server may be slow/long. Maybe you should increase the time-out value to be sure to not trigger it for nothing

**Comment by exiledkingcc** [comment]
> great. Just be aware that test running on the server may be slow/long. Maybe you should increase the time-out value to be sure to not trigger it for nothing

ok, i will increase timeout to 30, though 10s may be enough.

**Comment by pubpub-zz** [comment]
@MartinThoma 
this PR is all yours

**Comment by MartinThoma** [comment]
Very nice work @exiledkingcc :clap: Thank you :pray:

**Comment by MartinThoma** [comment]
I've just created a security advisory for this: https://github.com/py-pdf/pypdf/security/advisories/GHSA-4vvm-4w3v-6mr8

**Comment by ThiefMaster** [comment]
A release with the fix would be great, considering that Dependabot is now bothering users about this :)

**Comment by MartinThoma** [comment]
It is fixed in 3.9.0 and upwards (as stated above + in the advisory).

PyPDF2 users should migrate to pypdf.

**Pull request merged**
