### PR TITLE
ENH: Use `cryptography` for encryption/decryption as a fallback for PyCryptodome

### LINKED ISSUE #1998: Consider migrating to Cryptography
## Explanation

I help maintain a large Python distribution, which would like to use `pypdf` for reading encrypted PDFs, but would prefer not to include the additional dependency of PyCryptodome as we already include [Cryptography](https://cryptography.io/) for numerous other dependencies. Cryptography includes the same cryptographic primitives used in `pypdf` (AES and RC4), but is typically a smaller and more secure installation as it calls well vetted implementations rather than implementing them directly. It also is a dependency of `requests` via `urllib3`, and is [widely deployed](https://piptrends.com/compare/pycrypto-vs-pycryptodome-vs-cryptography). A quick check of conda-forge packages showed that PyCryptodome / PyCryptodomeEx was used in 25 packages versus 135 for Cryptography, and other packages such the [`pdfminer.six`](https://pdfminersix.readthedocs.io) have [made this migration earlier](https://github.com/pdfminer/pdfminer.six/pull/456).

If this is something that seems worthwhile, I can work on creating a PR for this effort. 

cc @exiledkingcc

### PR DESCRIPTION
**Pull request by exiledkingcc**
Use the [`cryptography` package](https://pypi.org/project/cryptography/) (maintained by the Python Cryptographic Authority, pyca) as a fallback if [PyCryptodome](https://pypi.org/project/pycryptodome/) (maintained by Legrandin / Helder Eijs) is not installed.

Closes #1998

### CODE REVIEW

**Comment by pubpub-zz** [comment]
@exiledkingcc 
canyou upgrade the workflow to add test with cryptography?

**Comment by MartinThoma** [comment]
Could you please also adjust https://github.com/py-pdf/pypdf/blob/main/docs/user/encryption-decryption.md (the comment about pycryptodome)?

Comparison of the two libraries:

* Maintainer(s): pycryptodome is just one mostly anonymous user, whereas [pyca is a PyPI organization](https://pypi.org/org/pyca/)
* [PyPI downloads](https://hugovk.github.io/top-pypi-packages/): cryptography has 156,673,182 downloads,  pycryptodome has 19,755,432
* Github Stars: [cryptography](https://github.com/pyca/cryptography) has 5.7k stars, [pycryptodome](https://github.com/Legrandin/pycryptodome) as 2.4k
* Github Forks: [cryptography](https://github.com/pyca/cryptography) has 1.6k, [pycryptodome](https://github.com/Legrandin/pycryptodome) as 0.4k

It seems to me that we should primarily use cryptography and only use pycryptodome as a fallback. What do you think @exiledkingcc ?

**Comment by exiledkingcc** [comment]
your opinion sounds very reasonable，i agree with it. but should contain it in the commit? then how about `pip install pypdf[crypto]` and ralated documents, will they should be changed in the commit also?

**Comment by MartinThoma** [comment]
It's ok for me if you leave it as it is. That is not a blocker.

The change of the default (from pycryptodome to cryptography) should probably be done AFTER I merge this one. Just to keep this PR fairly stable. I want to merge it on Friday evening / early Saturday.

**Comment by xilopaint** [comment]
@exiledkingcc @MartinThoma I can't understand, v3.14.0 release mentions this PR but `pip install "pypdf[crypto]"` still installs PyCryptodome instead of cryptography. What did I not understand well?

**Comment by exiledkingcc** [comment]
for now, cryptography is a fallback for PyCryptodome. it will change in the future, since cryptography seems more official.

> Also, could you guys clarify if cryptography is a pure-python library and if it handles AES encryption?
cryptography is a wrapper of openssl, not pure-python.

**Comment by xilopaint** [comment]
> for now, cryptography is a fallback for PyCryptodome. it will change in the future, since cryptography seems more official.

Does it mean for now we need `pip install cryptography` and `pip install pypdf[crypto]` will install `cryptography` in the future?

> cryptography is a wrapper of openssl, not pure-python.

Does it handle AES encryption?

**Comment by exiledkingcc** [comment]
for now，you can `pip install pypdf cryptography` to use cryptography in pypdf. in the future, `pip install pypdf[crypto]` will install cryptography automatically.

cryptography can handle AES, and many other algorithms.

**Comment by MartinThoma** [comment]
The [latest `cryptography`](https://pypi.org/project/cryptography/) does not support Python 3.6 anymore [since 41.0.0](https://cryptography.io/en/latest/changelog/). I'm not sure if that might be a blocker from changing the default.

There are still older versions, but I don't know if they are secure as they might have unfixed known bugs.

That is a pretty strong reason for me to drop Python 3.6 support.

**Comment by MartinThoma** [comment]
> Does [cryptography] handle AES encryption?

Yes: https://github.com/py-pdf/pypdf/blob/main/pypdf/_crypt_providers/_cryptography.py#L31

Just like PyCryptodome: https://github.com/py-pdf/pypdf/blob/main/pypdf/_crypt_providers/_pycryptodome.py#L30C1-L30C1

**Pull request merged**
