### PR TITLE
BUG: fix sheared image

### LINKED ISSUE #2411: Extracted image is being distorted
When extracting an image from some specific PDF file, the corresponding output file is distorted. Evince and *pdfimages* are able to extract correct images.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.14.21-150400.24.100-default-x86_64-with-glibc2.31

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf==3.17.4, crypt_provider=('local_crypt_fallback', '0.0.0'), PIL=10.1.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
from pypdf import PdfReader


for page in PdfReader('out1.pdf').pages:
    for image in page.images:
        if image.name == "Im15.png":
            image.image.save(image.name)
```

I have sent the PDF file to @MartinThoma directly for privacy reasons.

## Traceback

Nothing to see here, just a distorted image inside the image viewer.

### PR DESCRIPTION
**Pull request by pubpub-zz**
closes #2411

### CODE REVIEW

**Comment by stefan6419846** [comment]
Is there an easy way to craft a test for this without using the original restricted file?

**Comment by stefan6419846** [comment]
https://corpora.tika.apache.org/base/docs/govdocs1/938/938702.pdf-tika-938702.pdf apparently has been deleted and cannot be used directly anymore.

**Comment by stefan6419846** [comment]
Nearly minimal test file for this issue (thanks to @pubpub-zz for providing support with minimizing the embedded image): [tt.pdf](https://github.com/user-attachments/files/16624406/tt.pdf)

**Comment by pubpub-zz** [comment]
image:
tt

**Comment by pubpub-zz** [comment]
> https://corpora.tika.apache.org/base/docs/govdocs1/938/938702.pdf-tika-938702.pdf apparently has been deleted and cannot be used directly anymore.

in replacement:
[tika-938702.pdf](https://github.com/user-attachments/files/16624503/tika-938702.pdf)

**Review by stefan6419846 — APPROVED** [review]

**Pull request merged**
