### PR TITLE
DEV: Fix changelog for UTF-8 characters

### PR DESCRIPTION
**Pull request by stefan6419846**
`make_release.py` did not correctly handle UTF-8 characters before, for example `→`, which was rendered as `\xe2\x86\x92`: https://github.com/py-pdf/pypdf/commit/cc306ad6abfb232f6922a7f0e939831d6611d0b7 and https://github.com/py-pdf/pypdf/releases/tag/4.0.2

The reason is that `str(b"abc")` yields the string representation `"b'abc'"` of the bytes type instead of the actual string value we want here. Properly decoding the bytes using `b"abc".decode()` does indeed yield the correct result `"abc"`.

The `lines` variable before

```
['"cc306ad6abfb232f6922a7f0e939831d6611d0b7:::REL: 4.0.2:::Martin Thoma"', '"b7bfd0d7eddfd0865a94cc9e7027df6596242cf7:::BUG: Use NumberObject for /Border elements of annotations (#2451):::rsinger417"', '"8cacb0fc8fee9920b0515d1289e6ee8191eb3f21:::DOC: Document easier way to update metadata (#2454):::Stefan"', '"3fb63f7e3839ce39ac98978c996f3086ba230a20:::TST: Avoid catching not emitted warnings (#2429):::Stefan"', '"61b73d49778e8f0fb172d5323e67677c9974e420:::DOC: Typo `Polyline` \\xe2\\x86\\x92 `PolyLine` in adding-pdf-annotations.md (#2426):::CWKSC"', '"f851a532a5ec23b572d86bd7185b327a3fac6b58:::DEV: Bump codecov/codecov-action from 3 to 4 (#2430):::dependabot[bot]"']
```

and after:

```
['"cc306ad6abfb232f6922a7f0e939831d6611d0b7:::REL: 4.0.2:::Martin Thoma"', '"b7bfd0d7eddfd0865a94cc9e7027df6596242cf7:::BUG: Use NumberObject for /Border elements of annotations (#2451):::rsinger417"', '"8cacb0fc8fee9920b0515d1289e6ee8191eb3f21:::DOC: Document easier way to update metadata (#2454):::Stefan"', '"3fb63f7e3839ce39ac98978c996f3086ba230a20:::TST: Avoid catching not emitted warnings (#2429):::Stefan"', '"61b73d49778e8f0fb172d5323e67677c9974e420:::DOC: Typo `Polyline` → `PolyLine` in adding-pdf-annotations.md (#2426):::CWKSC"', '"f851a532a5ec23b572d86bd7185b327a3fac6b58:::DEV: Bump codecov/codecov-action from 3 to 4 (#2430):::dependabot[bot]"']
```

Especially have a look at the entry for #2426, which now renders correctly.

### CODE REVIEW

**Comment by stefan6419846** [comment]
I have added some basic test as well which covers the UTF-8 issue as well as the username issues from #2246. To simplify testing, the `rich` import has been made internal as I did not yet feel like updating the requirements files just for this ;)

**Review by MartinThoma — APPROVED** [review]
Very nice work Stefan! You're bringing our tooling on a whole new level :tada:

**Comment by MartinThoma** [comment]
Approved - feel free to merge whenever you want :-)

**Comment by stefan6419846** [comment]
I just do not like when changelogs have easy to fix issues ;) And trying to test even small tooling is something I consider essential - especially as these tools should "just work" and are more likely to not receive much love from the outside.

**Pull request merged**
