### PR TITLE
Rename create_viewer_preference

### PR DESCRIPTION
**Pull request by marcstober**
Proposed change to not include `create_viewer_preference` in the public API. Also fix some docstring typos.

See #2144

### CODE REVIEW

**Comment by stefan6419846** [comment]
Could you please replace the PR title with some more meaningful one? See https://pypdf.readthedocs.io/en/latest/dev/intro.html#commit-messages for additional information.

**Comment by marcstober** [comment]
@stefan6419846 sure, this is related to another recent change @pubpub-zz and @MartinThoma have been working on, so it would be good to get their feedback too. I'm not sure if this should also be ENH or STY or something else?

**Comment by pubpub-zz** [comment]
I'm not found of creating automatically the view_preference object:
a) it changes the behavior of the function between `PdfReader` and `PdfWriter` of  `viewer_preferences()`
b) if you really want to do the action in "one instruction" you just have to do it that way:
`     v = writer.viewer_preferences or writer.create_viewer_preference()`

**Comment by marcstober** [comment]
@pubpub-zz ok, I updated this pull request with just the rename discussed here: https://github.com/py-pdf/pypdf/issues/2105#issuecomment-1710491274

@MartinThoma I think this is ready to merge if it's OK with you and @pubpub-zz now?

> I'm not fond of creating automatically the view_preference object: a) it changes the behavior of the function between `PdfReader` and `PdfWriter` of `viewer_preferences()` b) if you really want to do the action in "one instruction" you just have to do it that way: ` v = writer.viewer_preferences or writer.create_viewer_preference()`

**Comment by pubpub-zz** [comment]
@marcstober 
this PR is now obsolete and overwritten by #2190 
isn't it ?

**Comment by marcstober** [comment]
@pubpub-zz yes, I'd originally thought this could be merged first

**Comment by pubpub-zz** [comment]
duplicate of #2190

**Comment by pubpub-zz** [comment]
less work for @MartinThoma already over busy 😉

**Pull request closed without merging**
