### PR TITLE
STY: Small readability increases

### PR DESCRIPTION
**Pull request by j-t-1**
Also remove unused DEFAULT_ANNOTATION_FLAG.

### CODE REVIEW

**Comment by j-t-1** [comment]
Python 3.8 added an = specifier to f-strings. This PR should work when Python 3.7 support is removed.

**Comment by stefan6419846** [comment]
I disagree with these changes and suggest closing it. Rationale:

* Having boolean variables with the `is_` prefix is fine and increases readability by making it clear that it is a boolean by just looking at the name.
* Unnecessarily dropping support for Python 3.7 for the sake of removing 20 characters (22 characters if taking into account that the equivalent call without the new formatting requires an additional `!r`) does not feel right.

**Comment by j-t-1** [comment]
Removed the = specifier to f-strings.

The name change makes
`if not is_external and not is_internal:`
quicker to parse
`if not external and not internal:`

**Comment by stefan6419846** [comment]
I do not really see the benefit you mention, thus I am going to keep this open for now.

**Comment by pubpub-zz** [comment]
agree with @stefan6419846

**Review by stefan6419846 — APPROVED** [review]

**Pull request merged**
