### PR TITLE
DOC: Improve slightly docstrings and documentation

### PR DESCRIPTION
**Pull request by j-t-1**

### CODE REVIEW

**Comment by j-t-1** [comment]
In classes `Ellipse` and `Rectangle`, can I change `interiour_color` to be `interior_color`?

**Comment by stefan6419846** [comment]
Renaming a parameter is only possible in accordance with our deprecation process.

**Comment by j-t-1** [comment]
> Renaming a parameter is only possible in accordance with our deprecation process.

Would this be how it is done?

```
class Ellipse(MarkupAnnotation):
    def __init__(
        self,
        rect: Union[RectangleObject, Tuple[float, float, float, float]],
        *,
        deprecate_with_replacement("interiour_color", "interior_color", "5.0.0")
        interiour_color: Optional[str] = None,
        **kwargs: Any,
    ):

```

Worth it?

**Comment by stefan6419846** [comment]
It seems like CI does not really like this, thus we might need to explicitly specify both parameters instead of using `kwargs.get`, although I am not sure why.

**Comment by j-t-1** [comment]
Is it to do with the placement of the * argument? Probably I need to also change in `rect=(50, 550, 200, 650), interiour_color="ff0000"` in tests/test_generic.py.

**Comment by stefan6419846** [comment]
The `*` usually divides positional and keyword only arguments. In general, the deprecation cannot be done unless we are sure that both the old and the new name work correctly.

**Comment by stefan6419846** [comment]
Regarding the separator behavior: Basically yes, see corresponding PEP 3102 as well.

The solution you propose basically is the same I have mentioned in https://github.com/py-pdf/pypdf/pull/2689#issuecomment-2134759931.

**Comment by j-t-1** [comment]
I agree. If the first commit was okay, you could merge just that, then I will do a fresh PR concentrating on this one variable name deprecation?

**Comment by stefan6419846** [comment]
Given the title, doing a separate PR for the deprecation sounds like the better idea. Then you can test your changes locally as well without any pressure.

**Comment by j-t-1** [comment]
Will do; does this mean you will merge the first commit?

**Pull request closed without merging**
