### PR TITLE
BUG: Fixed reference of value with str.__new__ in TextStringObject

### PR DESCRIPTION
**Pull request by thomas-forte**
based on comments from #2949 

- Fixing reference of value with str.__new__ output
- updated type annotation on update_page_form_field_values

### CODE REVIEW

**Comment by stefan6419846** [comment]
Could you please add a test which shows why this change is necessary?

**Comment by PJBrs** [comment]
I was running into the same issue and this PR fixes it. The code I'm working on sometimes writes an int value into a form, which up until recently worked without problem. I'd help out with writing a test, but my distro is pretty ancient in certain regards...

**Comment by stefan6419846** [comment]
As long as your distro supports running the latest *pypdf* version, id est at least Python 3.8, this should be no real issue in theory.

**Comment by PJBrs** [comment]
... or maybe existing tests can be altered a bit, like this:
```
@@ -1458,7 +1458,7 @@ def test_update_form_fields(tmp_path):
             "RdoS1": "/",
             "Combo1": "!!monCombo!!",
             "Liste1": "Liste2",
-            "Liste2": ["Lst1", "Lst3"],
+            "Liste2": [int(1), float(2.8), "Lst3"],
             "DropList1": "DropListe3",
         },
         auto_regenerate=False,
@@ -1487,7 +1487,7 @@ def test_update_form_fields(tmp_path):
     assert flds["RadioGroup1"]["/V"] == "/2"
     assert flds["RadioGroup1"]["/Kids"][0].get_object()["/AS"] == "/Off"
     assert flds["RadioGroup1"]["/Kids"][1].get_object()["/AS"] == "/2"
-    assert all(x in flds["Liste2"]["/V"] for x in ["Lst1", "Lst3"])
+    assert all(x in flds["Liste2"]["/V"] for x in ["1", "2.8", "Lst3"])
 
     assert all(x in flds["CheckBox1"]["/_States_"] for x in ["/Off", "/Yes"])
     assert all(x in flds["RadioGroup1"]["/_States_"] for x in ["/1", "/2", "/3"])

```

**Comment by stefan6419846** [comment]
I have just added some even simpler tests to the `TextStringObject` directly as *mypy* validation is not running on the tests anyway.

Regarding your test issues: Please make sure to install all required dependencies using `pip install -r requirements/ci.txt` beforehand. We depend on some *pytest* plugins which are reported as missing in your case.

**Review by stefan6419846 — APPROVED** [review]

**Comment by thomas-forte** [comment]
I'm sorry I wasn't on top of this, was dealing with family and holidays, but thank you for adding that simple test!

For me the type annotations and docstring's were not showing for this libraries context in my IDE. So while I was supplying an int or float sometimes I had no idea that was incorrect. It still worked on the previous releases, my app was using 3.9.1, before updating. Specifically it was introduced on the UTF16_BOM pull request when the __new__ method was added.

**Pull request merged**
