### PR TITLE
MAINT: Amend byte cache

### PR DESCRIPTION
**Pull request by j-t-1**
Cache string to byte conversions when the string length is greater than one.
#2726

### CODE REVIEW

**Comment by stefan6419846** [comment]
I am not sure if this really makes sense or what the original intent of the old implementation has been. Until this is more clear (see my comment in #2726), I recommend against merging this.

**Comment by j-t-1** [comment]
```
@pytest.mark.parametrize(
    ("input_str", "expected"),
    [
        ("foo", b"foo"),
        ("😀", "😀".encode()),
        ("‰", "‰".encode()),
        ("▷", "▷".encode()),
        ("世", "世".encode()),
        # A multi-character string example with non-latin-1 characters:
        ("😀😃", "😀😃".encode()),
    ],
)
def test_b(input_str: str, expected: str):
    assert pypdf._utils.b_(input_str) == expected
```

Should this be:
```
def test_b(input_str: str, expected: bytes):
    assert pypdf._utils.b_(input_str) == expected
```

**Comment by stefan6419846** [comment]
Isn't your new code the same? If you are referring to the decorator - no, this cannot be removed. This defines the parameters/sub-tests to use for the test.

**Comment by j-t-1** [comment]
My comment could have been better. The change is to the type of the second argument from str to bytes (keeping the decorator).

**Comment by stefan6419846** [comment]
Yes, the `expected` parameter should be bytes, as we are encoding the strings here.

**Comment by j-t-1** [comment]
The caching of the existing function is maybe deliberate.

**Pull request closed without merging**
