### PR TITLE
DOC: add readthedocs.yml and bump docs dependencies using `tox -e deps`

### PR DESCRIPTION
**Pull request by adehad**
Follow up to #1430 

Add the readthedocs config.

Hoping that adding the editable install inside the `docs.txt` is fine. I have an alternative option if it doesn't work.

### CODE REVIEW

**Comment by MartinThoma** [comment]
We did have issues with links in the past: https://github.com/py-pdf/pypdf/issues/1569

For that reason, we pinned myst-parser: https://github.com/py-pdf/pypdf/commit/6abb50e247ab4eeab0e3969a9fcb827d12cf4a94

Let's see if they are gone

**Comment by MartinThoma** [comment]
I'm uncertain if the `readthedocs.yml` is used at all. At least I don't see it being mentioned in the build logs.

**Comment by MartinThoma** [comment]
https://github.com/py-pdf/pypdf/issues/1569 is back. I revert the changes to the requirement files.

**Comment by MartinThoma** [comment]
I fixed it via https://github.com/py-pdf/pypdf/pull/1752 :-)

Thank you for your PR. Nudging me to use configuration files within the repository + enabling "build pull requests" is a good idea :+1: 

If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html :-)

**Comment by MartinThoma** [comment]
I cannot figure out how to make GitHub/Readthedocs add a message within the PR with a link to the built docs

The build docs are at https://readthedocs.org/projects/pypdf/builds/

**Comment by adehad** [comment]
It is normally added in the "Checks" for a PR, I think you can try it on my other PR (ie opening and closing the PR should re trigger the builds)

**Comment by adehad** [comment]
@MartinThoma it seems it didn't add to the other PR
I had a look at
https://docs.readthedocs.io/en/latest/guides/pull-requests.html

And it suggested that the integration needs OAuth access granted/checked. So might be worth double checking that too.

Sorry for the confusion

**Pull request merged**
