### PR TITLE
ROB: Capture UnicodeDecodeError at PdfReader.pdf_header

### LINKED ISSUE #1758: UnicodeDecodeError 'utf-8' codec can't decode byte 0xac in position 0: invalid start byte
While trying to merge 2 PDF's, I get the following error.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.4.0-144-generic-x86_64-with-glibc2.29

$ python -c "import pypdf;print(pypdf.__version__)"
3.7.0
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python

def merge_pdf(source_pdf, pdf_to_merge: list):
    """
    :param source_pdf:
    :param pdf_to_merge: list of pdf to append to source_pdf
    :return:
    """
    merger = PdfMerger(strict=False)
    items = [source_pdf]
    items.extend(pdf_to_merge)
    pdf_merged_buffer = io.BytesIO()
    for _pdf_file in items:
        # Append PDF files
        pdf_buffer = PdfReader(io.BytesIO(_pdf_file), strict=False)
        merger.append(pdf_buffer, import_outline=False)
    merger.write(pdf_merged_buffer)
    merger.close()

```

I can share the pdf over a private channel.

## Traceback
```
This is the Traceback I see, only adding the part with pypdf:
  File "/home/nalin/workspace/project/utils/pdf_utils.py", line 185, in merge_pdf
    merger.write(pdf_merged_buffer)
  File "/home/nalin/.virtualenv/project/lib/python3.8/site-packages/pypdf/_merger.py", line 333, in write
    self.output.add_page(page.pagedata)
  File "/home/nalin/.virtualenv/project/lib/python3.8/site-packages/pypdf/_writer.py", line 359, in add_page
    return self._add_page(page, list.append, excluded_keys)
  File "/home/nalin/.virtualenv/project/lib/python3.8/site-packages/pypdf/_writer.py", line 311, in _add_page
    other = page_org.pdf.pdf_header
  File "/home/nalin/.virtualenv/project/lib/python3.8/site-packages/pypdf/_reader.py", line 363, in pdf_header
    pdf_file_version = self.stream.read(8).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xac in position 0: invalid start byte
```

PDF can be opened with a PDF viewer.

### PR DESCRIPTION
**Pull request by MartinThoma**
Closes #1758

### CODE REVIEW

**Review by pubpub-zz — COMMENTED** [review]
I'm very confused about this PR : if the message can not be decoded it means it does not respect the standard, and having such an exception seems for me acceptable. If there is realy a problem, I would use use decode with 'backslashreplace' to have a better understanding of the non recognised 'magic' and eventy raise an error.

**Comment by MartinThoma** [comment]
I think I've noticed pdfs in the past where the version was not set (correctly), but the remaining document was just fine

**Comment by pubpub-zz** [comment]
> I think I've noticed pdfs in the past where the version was not set (correctly), but the remaining document was just fine

so what about just using  backslashreplace to be tolerant but still able to read the magic ?

**Comment by MartinThoma** [comment]
https://github.com/py-pdf/pypdf/pull/1768 is a better solution.

**Pull request closed without merging**
