### PR TITLE
ROB: fix extract_text() issues on damaged PDFs

### LINKED ISSUE #2702: local variable 'cm' referenced before assignment
Trying to extract text from page.
Tested in Win11 & Linux container.
pypdf==4.2.0, crypt_provider=('cryptography', '42.0.5'), PIL=none
## Traceback

```
File "/usr/local/lib/python3.10/site-packages/pypdf/_page.py", line 2052, in extract_text
    return self._layout_mode_text(
  File "/usr/local/lib/python3.10/site-packages/pypdf/_page.py", line 1950, in _layout_mode_text
    fonts = self._layout_mode_fonts()
  File "/usr/local/lib/python3.10/site-packages/pypdf/_page.py", line 1902, in _layout_mode_fonts
    *cmap, font_dict_obj = build_char_map(font_name, 200.0, self)
  File "/usr/local/lib/python3.10/site-packages/pypdf/_cmap.py", line 33, in build_char_map
    font_subtype, font_halfspace, font_encoding, font_map = build_char_map_from_dict(
  File "/usr/local/lib/python3.10/site-packages/pypdf/_cmap.py", line 58, in build_char_map_from_dict
    map_dict, space_code, int_entry = parse_to_unicode(ft, space_code)
  File "/usr/local/lib/python3.10/site-packages/pypdf/_cmap.py", line 235, in parse_to_unicode
    cm = prepare_cm(ft)
  File "/usr/local/lib/python3.10/site-packages/pypdf/_cmap.py", line 260, in prepare_cm
    if isinstance(cm, str):
UnboundLocalError: local variable 'cm' referenced before assignment
```

### PR DESCRIPTION
**Pull request by pubpub-zz**
closes #2702

### CODE REVIEW

**Comment by stefan6419846** [comment]
Is there something we can do about the coverage here?

**Comment by pubpub-zz** [comment]
The modification is properly test covered. The incomplete coverage is on the original condition but I do not see what is wrong. any ideas ?

**Comment by pubpub-zz** [comment]
@stefan6419846 ,?
even the new rewriting does not fix the coverage. no other solution than using pragma. OK for you?

**Comment by stefan6419846** [comment]
I recommend to remove the pragma in this case. It seems like we somehow end up with incomplete branch coverage, but it is not clear to me why. I will be merging this without the pragma in this case.

**Comment by stefan6419846** [comment]
Seems like there are some more changes required after the merge of *main*, as there are still references to the removed `b_`.

**Comment by pubpub-zz** [comment]
I 'm definitively not fond of the conflict managment through the web pages.
It is now fixed

**Review by stefan6419846 — APPROVED** [review]

**Pull request merged**
