### PR TITLE
TST: Replace pytest.mark.external by enable_socket

### PR DESCRIPTION
**Pull request by MartinThoma**
pypdf has three types of tests: (1) Tests that work only with the repository itself, (2) tests that require the sample-files git submodule, and (3) tests that require PDF documents from external websites.

As people or projects might not be able to execute (2), they are marked with `@pytest.mark.samples`

As people or projects might not be able to execute (3), they are marked with `@pytest.mark.enable_socket` (formerly @pytest.mark.external).

We regularly had issues with people forgetting to mark their tests with `external` (see #1632).

The [pytest-socket](https://pypi.org/project/pytest-socket/) pytest plugin disables the usage of sockets on the whole project, except for the tests marked with `enable_socket`. This was, we can guarantee that the CI will catch missing `@pytest.mark.enable_socket`.

### CODE REVIEW

**Comment by MartinThoma** [comment]
@dkg Please let me know what you think :-)

Sadly, this means that people using the `external` flag at the moment need to replace it.

Do you think we should have both flags for a while?

**Comment by MartinThoma** [comment]
The pytest plugin disabled network connections, except when this marker is set. Meaning CI would fail if the marker is missing, because the test cannot download the file. Hence this guarantees the we never forget to at the marker. But we might forget to remove it, if we get rid of the external file

**Comment by MasterOdin** [comment]
To add a bit more detail to what @MartinThoma said since I was curious how this worked, this PR adds the [pytest-socket](https://pypi.org/project/pytest-socket/) plugin to pytest, where by passing the `--disable-socket` flag to `pytest.addopts`, then all requests over a socket (be it HTTP or otherwise) will throw an error, unless you do `pytest.mark.enable_socket`, which is a special flag to the aforementioned plugin which then turns back on socket usage.

For any test that doesn't have that marker, we should see a `SocketBlockedError` get thrown, as we do right now in the CI with the last commit since I guess a test doesn't have it properly marked, which shows the value of this change.

**Comment by MartinThoma** [comment]
@dkg If it's helpful to you, I could make a release at a fixed time so that you can adjust the ignored pytest mark from `external` to `enable_socket` :-)

**Comment by MartinThoma** [comment]
@dkg The first version with that fix is now released. Meaning you will not have to worry about this issue again :-)

**Pull request merged**
