### PR TITLE
BUG: Fix incorrect tm_matrix in call to visitor_text

### PR DESCRIPTION
**Pull request by troethe**
Supply the old tm_matrix when flushing out `text` to the `visitor_text`
in `crlf_space_check`. The new one might already be changed and
unrelated to the current text.

Also add a test for the tm_matrix and cm_matrix that are given to
`visitor_text` when extracting text.
The test computes the coordinates of three letters in different
parts of a test page based on the matrices and checks, if they are
roughly where they should be.

Fixes py-pdf#2059

### CODE REVIEW

**Comment by MartinThoma** [comment]
@troethe From my side we are good to go :-) Please adjust the top comment of the PR in such a way that it can be the commit message of the squash-merge. For example:

```
Supply the old tm_matrix when flushing out `text` to the `visitor_text`
in `crlf_space_check`.

Check the coordinates computed from the tm_matrix and cm_matrix
that are given to `visitor_text` when extracting text.
The test computes the coordinates of three letters in different
parts of a test page based on the matrices given to the `visitor_text`
function and checks, if they are roughly where they should be.

Fixes #2059
```

One last question:

> A preliminary fix to https://github.com/py-pdf/pypdf/issues/2059

What do you mean by "preliminary"? Doesn't this fix the mentioned issue?

**Comment by MartinThoma** [comment]
@pubpub-zz I guess this PR is fine from your perspective?

**Comment by troethe** [comment]
> What do you mean by "preliminary"? Doesn't this fix the mentioned issue?

Yes, it does, but when I originally submitted this, I didn't quite understand all of the code yet and I had not thoroughly tested it as shown by the fact that it ended up not being quite right. I guess I should have called it a WIP/draft instead.

**Comment by MartinThoma** [comment]
Ok, then please let me know when you think I can merge :-)

**Comment by troethe** [comment]
@MartinThoma Ok, I think it's good now!
Sorry for those last unnecessary pushes. I misread and thought you wanted me to update the top commit's message instead of the PR's top comment.

**Comment by MartinThoma** [comment]
No problem :-) 

Thank you for the contribution :pray:  I will make a release that contains it today

**Comment by MartinThoma** [comment]
If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html :-)

**Comment by troethe** [comment]
> If you want, I can add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html :-)

Sure, why not. :) Thank you!

**Pull request merged**
