### PR TITLE
CMYK indexed color to encrypt/decrypt

### PR DESCRIPTION
**Pull request by pilotandy**
RE: https://github.com/py-pdf/pypdf/issues/2188

### CODE REVIEW

**Comment by pilotandy** [comment]
Imagemagic failures. I'm not sure about those.

**Comment by pubpub-zz** [comment]
I tried it and the error did not occur... maybe a random error during the pytest run
can you try to commit a small change commit and undo it before commit again to rerun the actions

**Comment by pubpub-zz** [comment]
@pilotandy 
I'm on your problem for a couple of hours. The problem is coming from your test file : getting the image scrumble either pypdf or pillow (not identified which one yet).🤔🤔🤔
Your mod was good👍

**Comment by pilotandy** [comment]
I thought maybe it was something I broke on my end. So I created a clean fork, venv, using python 3.8, I still get failures without any code changes. Anyway, the new PR simply comes from that new fork. Added some comments too.

**Pull request closed without merging**
