### PR TITLE
ENH: Added encoding ability

### PR DESCRIPTION
**Pull request by coolbombom**
Added encoding ability to update_page_form_field_values so functionality uses that encoding to populate from fields.

Fixes issue that i had:
https://github.com/py-pdf/pypdf/issues/2035

### CODE REVIEW

**Comment by pubpub-zz** [comment]
@coolbombom 
From my analysis the mod is more tricky. Can you try this PR : #2047  (note this PR requires the latest night built to ensure to have 
 #2043 )

**Comment by pubpub-zz** [comment]
@MartinThoma 
this is not a feature but a (wrong from my point of view) way to work around german characters encoding. the encoding is a consequence of the font selected.

**Comment by coolbombom** [comment]
@pubpub-zz 
I can confirm that https://github.com/py-pdf/pypdf/pull/2047 fixes the issue

**Comment by pubpub-zz** [comment]
I therefore propose to clise those PR

**Pull request closed without merging**
