### PR TITLE
REL: 5.1.0

### PR DESCRIPTION
**Pull request by stefan6419846**
After one moment, creating a new release seems like a good idea.

As usual, please do not merge directly after approving to use the correct commit body.

### CODE REVIEW

**Review by pubpub-zz — APPROVED** [review]

**Comment by pubpub-zz** [comment]
@MartinThoma  / @stefan6419846 
I let you merge : If you want to try any possible fix for the tag create issue

**Comment by stefan6419846** [comment]
This time we got another CI error as well:

```
/home/runner/work/_temp/042f3e83-3caa-4fd1-b3b4-0e81bf8e12d2.sh: line 38: layout_mode_font_height_weight: command not found
/home/runner/work/_temp/042f3e83-3caa-4fd1-b3b4-0e81bf8e12d2.sh: command substitution: line 39: syntax error: unexpected end of file
```

I have pushed the tag manually and it seems like signing worked here as well, although I got an error message from GitHub:

```
remote: Bypassed rule violations for refs/tags/5.1.0:
remote: 
remote: - Cannot create ref due to create name restrictions.
remote: 
```

**Comment by pubpub-zz** [comment]
> I have pushed the tag manually and it seems like signing worked here as well, although I got an error message from GitHub:
> 
> ```
> remote: Bypassed rule violations for refs/tags/5.1.0:
> remote: 
> remote: - Cannot create ref due to create name restrictions.
> remote:
> ```

Can you tell me how you pushed it ?

**Comment by stefan6419846** [comment]
Nothing special:

```
$ git tag -s "5.1.0" -eF RELEASE_COMMIT_MSG.md
$ git push origin 5.1.0 
```

**Pull request merged**
