### PR TITLE
DOC: Small changes to PaperSize notes

### PR DESCRIPTION
**Pull request by j-t-1**
Plus one typo in xmp.py.

### CODE REVIEW

**Comment by j-t-1** [comment]
This could also be amended, but unsure how to do so:

`# Additionally, A0 is defined to have an area of 1 m**2
`

**Review by pubpub-zz — DISMISSED** [review]

**Comment by pubpub-zz** [comment]
> This could also be amended, but unsure how to do so:
> 
> `# Additionally, A0 is defined to have an area of 1 m**2 `

what about adding link to https://en.wikipedia.org/wiki/ISO_216

**Comment by j-t-1** [comment]
> > This could also be amended, but unsure how to do so:
> > `# Additionally, A0 is defined to have an area of 1 m**2 `
> 
> what about adding link to https://en.wikipedia.org/wiki/ISO_216

Good idea; done.

**Comment by stefan6419846** [comment]
It seems like the last commit did not went through?

**Review by stefan6419846 — APPROVED** [review]

**Pull request merged**
