### PR TITLE
TST : move test before others to prevent errors

### PR DESCRIPTION
**Pull request by pubpub-zz**
detected in #2228

### CODE REVIEW

**Comment by pubpub-zz** [comment]
@stefan6419846 
Based on your analysis I've simply moved the test at very first. This makes it work

**Comment by pubpub-zz** [comment]
@MartinThoma 
this could be an alternative to #2229
up to you

**Comment by MartinThoma** [comment]
Ah, I didn't notice that when I merged. I'll check :-)

**Comment by MartinThoma** [comment]
Thanks for the hint!

**Comment by stefan6419846** [comment]
While this might work for this specific case, I still do not think that this is a clean solution either, as all code should be side-effect free ideally. As soon as I would use the features of `pytest-randomly` for example, the tests would become unstable again.

**Comment by MartinThoma** [comment]
I agree, the order of tests should not matter. I'm closing this PR as we solved the issue via #2229. Thank you for jumping in that quickly again @pubpub-zz an proposing a solution :pray:

**Comment by MartinThoma** [comment]
@stefan6419846 I'm open for the idea of addng `pytest-xdist` :-) That would speed up our CI wall clock time + have a similar effect t pytest-randomly

**Comment by stefan6419846** [comment]
@MartinThoma I am not sure whether we can actually deploy `pytest-xdist` here without breaking stuff, at least as long as we are re-using files from the PDF caching mechanism. We could have (potential) sporadic failures due to simultaneous file operations unless we can ensure that all operations on a file are atomic.

**Comment by MartinThoma** [comment]
I see the argument for writing the file, e.g. that a a file could be partially written to the cache and another process tries to read it before it is completely written.

`download_test_pdfs` is executed by CI before any tests and should solve that issue (but we still would need to add all files there).

Do you think parallel reads are an issue?

**Comment by stefan6419846** [comment]
No, I only see parallel downloads/writes of the same files as an issue (maybe leading to subsequent read issues), while pure read operations on existing files or files only used once anyway should work.

**Pull request closed without merging**
