### PR TITLE
ENH: Add transform method to Transformation

### PR DESCRIPTION
**Pull request by rrthomas**
I am the maintainer of [PSUtils](https://github.com/rrthomas/psutils). I am adding PDF support, and rewriting the code in Python. pyPDF was a significant motivation for the choice of language, so thanks for that!

I need to express vertical and horizontal page flips, and the simplest way to achieve this seemed to be to add a general `transform` method to `Transformation` (I need all the different sorts of transformations to be applied repeatedly to the same page, so it's easier to change a `Transformation` than to make multiple copies of a page and transform that.) I have done this in the simplest way I could; it might be desired for the method to take a `CompressedTransformationMatrix` too.

If you agree to add an API something like this, I'll happily add some tests. (At the moment I just tested it with my experimental PSUtils code.)

### CODE REVIEW

**Comment by pubpub-zz** [comment]
sounds good to me too. 
A good example may be required to show users the way to use it

**Comment by pubpub-zz** [comment]
@rrthomas 
👍 ❤️

**Comment by rrthomas** [comment]
`tox.ini` seems to be missing a dependency, `pytest-socket`.

**Comment by MartinThoma** [comment]
Thank you for your contribution @rrthomas! If you want, I'll also add you to https://pypdf.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by MartinThoma** [comment]
The PR was just merged to `main`. It will be part of the release this weekend (`pypdf==3.8.0`)

**Comment by rrthomas** [comment]
Thanks very much, I'd be delighted to be added to the contributors list, and I look forward to using the release!

**Pull request merged**
