### PR TITLE
Update writer class

### PR DESCRIPTION
**Pull request by HannahNgx**
Added correct_annotation_encodings method in writer class to automatically deal with issue where output PDF form with undefined '/Encoding' in the "/DR" section in the fields/annotations.
It will be called in the clone_document_from_reader after clone_reader_document_root is called

### CODE REVIEW

**Comment by stefan6419846** [comment]
Thanks for your PR. Could you please add an example file as well? Additionally, I do not really like the deep nesting. Are you able to simplify this with early exits?

**Comment by pubpub-zz** [comment]
@HannahNgx 
a) Are you dealing with #2577 ? if so, please update your first comment to address it
b) Are you facing this issue on other documents to propose such a PR?

The issue #2577 is dealing with a "damaged" PDF which is not respecting the PDF format : the "/Encoding" tag is not at the good position ("/DR" should not include an encoding field, but it should be within font). I see no reason to call your new `correct_annotation_encodings` on each import : We may have undetected side effects.

From my point of view, instead of adding a very specific repair tool, it might be better to fix the creation tool. Else It might be better to propose it as a tool included in https://github.com/py-pdf/pdfly

**Comment by pubpub-zz** [comment]
@HannahNgx 
any progress ?

**Comment by pubpub-zz** [comment]
In order to clean up, I close this PR. Feel free to propose a new version if you wish

**Pull request closed without merging**
