### PR TITLE
ROB: Ignore EOF in NumberObject.read_from_stream

### PR DESCRIPTION
**Pull request by rraval**
Use `ignore_eof=True` just like `NameObject` does, which is the only other caller to `read_until_regex` in this module.

This helps prevent arcane exceptions when trying to parse a number:

```
PyPDF2.errors.PdfStreamError: Stream has ended unexpectedly
```

The motivation is essentially identical to the change that introduced `ignore_eof=True` on `NameObject`s:
https://github.com/py-pdf/PyPDF2/commit/431ba7092037af7d1c296f8f280aca167859ce61

### CODE REVIEW

**Comment by rraval** [comment]
Sadly I do not have a reproducing PDF that I can add to the testing corpus. This came up when exercising `PdfMerger` with a bunch of private files.

**Comment by rraval** [comment]
Hi there, I've rebased the branch off the latest `main` to permit clean fast-forward merging. Hopefully this can get upstreamed soon.

**Review by MasterOdin — COMMENTED** [review]
So now all usages of `read_until_regex` override the default `ignore_eof` value of `False`, right? If we're going this route, should probably then flip the default value to `True` and then remove using the third argument in the two places...

**Comment by rraval** [comment]
> So now all usages of `read_until_regex` override the default `ignore_eof` value of `False`, right? If we're going this route, should probably then flip the default value to `True` and then remove using the third argument in the two places...

I've opened a separate PR along these lines: https://github.com/py-pdf/pypdf/pull/1521

Feel free to pick one and close out the other. I'm not familiar enough with this codebase to judge which is "better".

**Comment by MartinThoma** [comment]
I'm closing this one as the parameter was now removed :-)

**Pull request closed without merging**
