### PR TITLE
ENH: Add AES support for encrypting PDF files

### PR DESCRIPTION
**Pull request by MartinThoma**
* PdfWriter.encrypt: Add 'algorithm' parameter
* PdfWriter: Add _encryption property
* PdfWriter: Add _encrypt_entry property

This change was made in another PR to avoid merge conflicts / get it merged soon. Full credit for the work goes to exiledkingcc in #1816

### CODE REVIEW

**Comment by xilopaint** [comment]
I can't understand. Wasn't AES encryption already supported?

**Comment by MartinThoma** [comment]
Decryption was supported, but not encryption.

**Comment by xilopaint** [comment]
Will `pypdf.PdfWriter.encrypt` use AES by default from now on?

**Comment by MartinThoma** [comment]
Not until `pypdf==4.0.0`. Using AES requires pycryptodome. That means if I change the default behavior, it would be a breaking change.

But with `pypdf==4.0.0` I definitely want to make it the default as using the RC4 encryption is insecure.

**Comment by xilopaint** [comment]
So will Pycryptodome be a mandatory dependency?

**Comment by MartinThoma** [comment]
No, Pycryptodome is not mandatory and will stay optional.

However, if you want to use modern encryption, you will need it.

**Pull request merged**
