### PR TITLE
DEV: Delete tox.ini

### PR DESCRIPTION
**Pull request by j-t-1**
Add Python 3.11, 3.12, remove 3.6

### CODE REVIEW

**Comment by pubpub-zz** [comment]
is this file used for coverage analysis ?

**Comment by stefan6419846** [comment]
AFAIK no, although it seems like we have a section about testing with *tox* in our testing docs. The coverage configuration is https://github.com/py-pdf/pypdf/blob/683aecac53738e2b71a0e2f0a8a12a112e63aa6d/pyproject.toml#L85-L112

**Comment by pubpub-zz** [comment]
what about preparing a PR to remove the file, merge and check if all ok and revert if observing side effect ?
@MartinThoma  any ideas about ?

**Comment by pubpub-zz** [comment]
@MartinThoma 
+1 ?

**Comment by j-t-1** [comment]
@stefan6419846 I deleted this accidentally, and then restored it.

> If you want to get a coverage report that considers the Python version specific
> code, you can run [`tox`](https://tox.wiki/en/latest/). [[testing.md](https://github.com/py-pdf/pypdf/blob/a195cb3587577fba8329a767f5a8c9fabd16d7dc/docs/dev/testing.md)]

It probably is not in the automated testing because it is time consuming to run (although I have not tested this!).
We could keep tox.ini and run it before releases.

**Comment by stefan6419846** [comment]
We are not using `tox` for CI, but GitHub Actions and their workflow matrix, which basically is the same. IMHO having the separate CI jobs instead of letting `tox` iterate over all Python installations drastically improves readability.

`tox` might be used for local development purposes, but I would argue that most of us do not want to test multiple Python versions locally or do not even have multiple Python versions installed, thus rendering it more or less useless.

**Comment by j-t-1** [comment]
> We are not using `tox` for CI, but GitHub Actions and their workflow matrix, which basically is the same. IMHO having the separate CI jobs instead of letting `tox` iterate over all Python installations drastically improves readability.
> 
> `tox` might be used for local development purposes, but I would argue that most of us do not want to test multiple Python versions locally or do not even have multiple Python versions installed, thus rendering it more or less useless.

Makes sense. If others agree we should delete tox.ini; if we keep it, then this PR would be okay.

**Comment by pubpub-zz** [comment]
I agree : let's change the PR to delete tox.ini

**Review by stefan6419846 — APPROVED** [review]

**Pull request merged**
