### PR TITLE
BUG: Fix conversion from 1 to LA

### LINKED ISSUE #2165: ValueError: conversion from 1 to LA not supported
## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
macOS-13.4.1-arm64-arm-64bit

$ python -c "import pypdf;print(pypdf._debug_versions)"
pypdf 3.14.0

# though i got this:
$ python -c "import pypdf;print(pypdf._debug_versions)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pypdf' has no attribute '_debug_versions'
```

## Code + PDF
Was extracting text from images with clown_sort (see my other filed issues).
[whitepaper WBT token blockchain whitepaper.pdf](https://github.com/py-pdf/pypdf/files/12543290/whitepaper.WBT.token.blockchain.whitepaper.pdf)

## Traceback

```
  ➤ ValueError: conversion from 1 to LA not supported while parsing embedded image 1 on page 14...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/uzoreus/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/sit │
│ e-packages/PIL/Image.py:1835 in putalpha                                                         │
│                                                                                                  │
│   1832 │   │   │   try:                                                                          │
│   1833 │   │   │   │   mode = getmodebase(self.mode) + "A"                                       │
│   1834 │   │   │   │   try:                                                                      │
│ ❱ 1835 │   │   │   │   │   self.im.setmode(mode)                                                 │
│   1836 │   │   │   │   except (AttributeError, ValueError) as e:                                 │
│   1837 │   │   │   │   │   # do things the hard way                                              │
│   1838 │   │   │   │   │   im = self.im.convert(mode)                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: image has wrong mode

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/uzoreus/workspace/clown_sort/clown_sort/files/pdf_file.py:61 in extracted_text            │
│                                                                                                  │
│    58 │   │   │   │                                                                              │
│    59 │   │   │   │   # Extracting images is a bit fraught (lots of PIL and pypdf exceptions h   │
│    60 │   │   │   │   try:                                                                       │
│ ❱  61 │   │   │   │   │   for image_number, image in enumerate(page.images, start=1):            │
│    62 │   │   │   │   │   │   image_name = f"Page {page_number}, Image {image_number}"           │
│    63 │   │   │   │   │   │   self._log_to_stderr(f"   Processing {image_name}...")              │
│    64 │   │   │   │   │   │   page_buffer.print(Panel(image_name, expand=False))                 │
│                                                                                                  │
│ /Users/uzoreus/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/sit │
│ e-packages/pypdf/_page.py:2633 in __iter__                                                       │
│                                                                                                  │
│   2630 │                                                                                         │
│   2631 │   def __iter__(self) -> Iterator[ImageFile]:                                            │
│   2632 │   │   for i in range(len(self)):                                                        │
│ ❱ 2633 │   │   │   yield self[i]                                                                 │
│   2634 │                                                                                         │
│   2635 │   def __str__(self) -> str:                                                             │
│   2636 │   │   p = [f"Image_{i}={n}" for i, n in enumerate(self.ids_function())]                 │
│                                                                                                  │
│ /Users/uzoreus/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/sit │
│ e-packages/pypdf/_page.py:2629 in __getitem__                                                    │
│                                                                                                  │
│   2626 │   │   │   index = len_self + index                                                      │
│   2627 │   │   if index < 0 or index >= len_self:                                                │
│   2628 │   │   │   raise IndexError("sequence index out of range")                               │
│ ❱ 2629 │   │   return self.get_function(lst[index])                                              │
│   2630 │                                                                                         │
│   2631 │   def __iter__(self) -> Iterator[ImageFile]:                                            │
│   2632 │   │   for i in range(len(self)):                                                        │
│                                                                                                  │
│ /Users/uzoreus/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/sit │
│ e-packages/pypdf/_page.py:534 in _get_image                                                      │
│                                                                                                  │
│    531 │   │   │   │   │   raise KeyError("no inline image can be found")                        │
│    532 │   │   │   │   return self.inline_images[id]                                             │
│    533 │   │   │                                                                                 │
│ ❱  534 │   │   │   imgd = _xobj_to_image(cast(DictionaryObject, xobjs[id]))                      │
│    535 │   │   │   extension, byte_stream = imgd[:2]                                             │
│    536 │   │   │   f = ImageFile(                                                                │
│    537 │   │   │   │   name=f"{id[1:]}{extension}",                                              │
│                                                                                                  │
│ /Users/uzoreus/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/sit │
│ e-packages/pypdf/filters.py:1040 in _xobj_to_image                                               │
│                                                                                                  │
│   1037 │   │   │   │   alpha = alpha.convert("L")                                                │
│   1038 │   │   │   if img.mode == "P":                                                           │
│   1039 │   │   │   │   img = img.convert("RGB")                                                  │
│ ❱ 1040 │   │   │   img.putalpha(alpha)                                                           │
│   1041 │   │   if "JPEG" in image_format:                                                        │
│   1042 │   │   │   extension = ".jp2"                                                            │
│   1043 │   │   │   image_format = "JPEG2000"                                                     │
│                                                                                                  │
│ /Users/uzoreus/Library/Caches/pypoetry/virtualenvs/clown-sort-zLqmJuxs-py3.11/lib/python3.11/sit │
│ e-packages/PIL/Image.py:1838 in putalpha                                                         │
│                                                                                                  │
│   1835 │   │   │   │   │   self.im.setmode(mode)                                                 │
│   1836 │   │   │   │   except (AttributeError, ValueError) as e:                                 │
│   1837 │   │   │   │   │   # do things the hard way                                              │
│ ❱ 1838 │   │   │   │   │   im = self.im.convert(mode)                                            │
│   1839 │   │   │   │   │   if im.mode not in ("LA", "PA", "RGBA"):                               │
│   1840 │   │   │   │   │   │   raise ValueError from e  # sanity check                           │
│   1841 │   │   │   │   │   self.im = im                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: conversion from 1 to LA not supported

```

### LINKED ISSUE #2176: Bug with pdfly extract-images: ValueError: conversion from 1 to LA not supported
Hi!

This problem was spotted in https://github.com/py-pdf/pypdf/pull/2170:
https://github.com/py-pdf/pypdf/blob/issue-2160/tests/test_cli.py#L91

I was able to quickly reproduce it with [`pdfly`](https://github.com/py-pdf/pdfly),
but the underlying bug is in `pypdf`:

## Reproduction steps
```
pdfly extract-images box.pdf
```
PDF file source: https://github.com/py-pdf/pypdf/blob/main/resources/box.pdf

## Traceback
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/typer/main.py", line 72, in except_hook
    rich_tb = Traceback.from_exception(
TypeError: from_exception() got an unexpected keyword argument 'suppress'

Original exception was:
Traceback (most recent call last):
  File "~/.local/lib/python3.8/site-packages/PIL/Image.py", line 1853, in putalpha
    self.im.setmode(mode)
ValueError: image has wrong mode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/bin/pdfly", line 8, in <module>
    sys.exit(entry_point())
  File "~/.local/lib/python3.8/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "~/.local/lib/python3.8/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/typer/core.py", line 778, in main
    return _main(
  File "~/.local/lib/python3.8/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "~/.local/lib/python3.8/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "~/.local/lib/python3.8/site-packages/pdfly/cli.py", line 62, in extract_images
    pdfly.extract_images.main(pdf)
  File "~/.local/lib/python3.8/site-packages/pdfly/extract_images.py", line 17, in main
    for image_file_object in page0.images:
  File "/opt/pypdf/pypdf/_page.py", line 2644, in __iter__
    yield self[i]
  File "/opt/pypdf/pypdf/_page.py", line 2640, in __getitem__
    return self.get_function(lst[index])
  File "/opt/pypdf/pypdf/_page.py", line 555, in _get_image
    return self._get_image(ids, cast(DictionaryObject, xobjs[id[0]]))
  File "/opt/pypdf/pypdf/_page.py", line 544, in _get_image
    imgd = _xobj_to_image(cast(DictionaryObject, xobjs[id]))
  File "/opt/pypdf/pypdf/filters.py", line 1100, in _xobj_to_image
    img.putalpha(alpha)
  File "~/.local/lib/python3.8/site-packages/PIL/Image.py", line 1856, in putalpha
    im = self.im.convert(mode)
ValueError: conversion from 1 to LA not supported
```

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29

$ pdfly --version
pdfly 0.2.14
  using pypdf==3.15.5
```

### PR DESCRIPTION
**Pull request by pubpub-zz**
Closes #2165
Closes #2176

### CODE REVIEW

**Comment by pubpub-zz** [comment]
@MartinThoma 
During pre-commit I've got the following issues reported:
>pypdf\filters.py:795:5: C901 `_xobj_to_image` is too complex (55 > 54)
>pypdf\filters.py:795:5: PLR0915 Too many statements (178 > 176)
>tests\test_writer.py:1607:9: S603 `subprocess` call: check for execution of untrusted input
>Found 4 errors (1 fixed, 3 remaining).

**Comment by pubpub-zz** [comment]
@MartinThoma 
this PR is all yours. Can you fix this issue ?

**Comment by stefan6419846** [comment]
I cannot see the third violation in CI (this should be related to the `subprocess` call for the watermark rendering, where there is an non-fixable error raised regardless of how the call is made).

For the other issues, see #2108. You should either refactor the code to reduce complexity or be able to justify why the increased complexity is necessary and cannot be avoided.

**Comment by pubpub-zz** [comment]
> I cannot see the third violation in CI (this should be related to the `subprocess` call for the watermark rendering, where there is an non-fixable error raised regardless of how the call is made).
> 
> For the other issues, see #2108. You should either refactor the code to reduce complexity or be able to justify why the increased complexity is necessary and cannot be avoided.

the refactoring required is too important to be part of this PR : this will require an idenpendant PR. about the subprocess it should be part of an independant PR too for traceeability

**Comment by stefan6419846** [comment]
You are not asked to do the refactoring of the complete code, but only for the corresponding section. I do not really see why this cannot be part of this PR - the chosen approach is to slowly refactor the sections which are changed anyway to not do everything at once. And as you are working on the corresponding code section, you already show that you understand enough of it to be able to safely refactor it, assuming that our test coverage is sufficient.

And as already mentioned: The `subprocess` violation you see should not even occur and cannot be seen in the CI style checks, as it should be ignored due to the `noqa` marker in the correspondig line already. If you experience issues on your personal device with pre-commit stuff, there seems to be some issue with your setup or with the pre-commit handling (where I do not have any real knowledge about).

**Comment by MartinThoma** [comment]
The two style issues we currently see are

```
pypdf/filters.py:795:5: C901 `_xobj_to_image` is too complex (55 > 54)
pypdf/filters.py:795:5: PLR0915 Too many statements (178 > 176)
```

I'll check how we can change that :-)

**Comment by MartinThoma** [comment]
Good work @pubpub-zz :+1:

**Comment by MartinThoma** [comment]
I like that the PR is clean / minimal. It was a good decision to not include refactoring in it, as that would have made the review way more complex. I'll take care of that now

**Comment by stefan6419846** [comment]
This probably is a matter of taste: In general, projects prefer the current contributor to fix all issues introduced with the current PR from what I have seen in the past (my GitHub activity is non-representative here). Maybe I am a bit opinionated about this as well due to doing a lot of code quality stuff.

In the end, it is up to you as the maintainer to decide on how you handle this, as long as this is a consistent behaviour which is applied equally to all changes.

**Comment by MartinThoma** [comment]
Typically, I would agree that issues should be fixed within the PR. However,  there are some exceptions:

* Value trade-off: If the value added by the PR is bigger than the issue it introduced, I don't want to block the PR. 
* PR readability: I like refactorings to be in separate PRs as it makes them so much easier to understand.

**Pull request merged**
