### PR TITLE
BUG: Handle single element ColorSpace list

### LINKED ISSUE #2023: Colorspace /DeviceRGB not supported
## Explanation

At the moment, support for the `/DeviceRGB` color mode seems to be missing:

```
File "/home/user/lib/python3.6/site-packages/pypdf/_page.py", line 2604, in __iter__
    yield self[i]
  File "/home/user/lib/python3.6/site-packages/pypdf/_page.py", line 2600, in __getitem__
    return self.get_function(lst[index])
  File "/home/user/lib/python3.6/site-packages/pypdf/_page.py", line 533, in _get_image
    return self._get_image(ids, cast(DictionaryObject, xobjs[id[0]]))
  File "/home/user/lib/python3.6/site-packages/pypdf/_page.py", line 522, in _get_image
    imgd = _xobj_to_image(cast(DictionaryObject, xobjs[id]))
  File "/home/user/lib/python3.6/site-packages/pypdf/filters.py", line 877, in _xobj_to_image
    "",
  File "/home/user/lib/python3.6/site-packages/pypdf/filters.py", line 693, in _get_imagemode
    mode_map.get(color_space)  # type: ignore
TypeError: unhashable type: 'ArrayObject'
```

Debugging the value of `color_space` reveals `['/DeviceRGB']`.

## Code Example

```python
from pypdf import PdfReader

reader = PdfReader('file.pdf')
for page in reader.pages:
    for image in reader.images:
        print(image)
```

### PR DESCRIPTION
**Pull request by pubpub-zz**
fixes #2023

### CODE REVIEW

**Comment by pubpub-zz** [comment]
@MartinThoma  all yours

**Comment by MartinThoma** [comment]
Thank you :-) 

What does "singleton" refer to in this context?

**Comment by pubpub-zz** [comment]
set on 1 item only, 😉

**Comment by MartinThoma** [comment]
Nice! Thank you for the fix and the explanation :pray: :-)

**Comment by pubpub-zz** [comment]
image
😤🤣🤣🤣🤣🤣🤣

**Comment by MartinThoma** [comment]
I only knew the computer science definition: A design pattern that restricts the instantiation of a class to a single object :smile:

**Pull request merged**
